/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quanlynhanvien.ui;

import javax.swing.JFrame;

/**
 *
 * @author User
 */
public class HomeForm extends javax.swing.JFrame {

    /**
     * Creates new form HomeForm
     */
    public HomeForm() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_TieuDe_QLNV = new javax.swing.JPanel();
        lbl_TieuDe_QLNV = new javax.swing.JLabel();
        pn_Menu_QLNV = new javax.swing.JPanel();
        btn_TrangChu_QLNV = new javax.swing.JButton();
        btn_QLKH_QLNV = new javax.swing.JButton();
        btn_QLNV_QLNV = new javax.swing.JButton();
        btn_QLSP_QLNV = new javax.swing.JButton();
        btn_QLHD_QLNV = new javax.swing.JButton();
        btn_ThongKe_QLNV = new javax.swing.JButton();
        btn_TaiKhoan_QLNV = new javax.swing.JButton();
        pn_TaiKhoan_Menu = new javax.swing.JPanel();
        lbl_Hinh_Menu = new javax.swing.JLabel();
        lbl_TenTaiKhoan_Menu = new javax.swing.JLabel();
        lbl_ChucVu_Menu = new javax.swing.JLabel();
        btn_DoiMK_Menu = new javax.swing.JButton();
        btn_DangXuat_Menu = new javax.swing.JButton();
        pn_Hinh = new javax.swing.JPanel();
        lbl_Hinh = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1540, 808));

        pn_TieuDe_QLNV.setBackground(new java.awt.Color(0, 255, 255));

        lbl_TieuDe_QLNV.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbl_TieuDe_QLNV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_TieuDe_QLNV.setText("Trí Tuệ Việt");
        lbl_TieuDe_QLNV.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbl_TieuDe_QLNV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pn_TieuDe_QLNVLayout = new javax.swing.GroupLayout(pn_TieuDe_QLNV);
        pn_TieuDe_QLNV.setLayout(pn_TieuDe_QLNVLayout);
        pn_TieuDe_QLNVLayout.setHorizontalGroup(
            pn_TieuDe_QLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_TieuDe_QLNVLayout.createSequentialGroup()
                .addComponent(lbl_TieuDe_QLNV, javax.swing.GroupLayout.DEFAULT_SIZE, 1530, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_TieuDe_QLNVLayout.setVerticalGroup(
            pn_TieuDe_QLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_TieuDe_QLNVLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_TieuDe_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btn_TrangChu_QLNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_TrangChu_QLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-home-page-40.png"))); // NOI18N
        btn_TrangChu_QLNV.setText("         Trang chủ");
        btn_TrangChu_QLNV.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btn_TrangChu_QLNV.setMinimumSize(new java.awt.Dimension(97, 90));
        btn_TrangChu_QLNV.setPreferredSize(new java.awt.Dimension(97, 90));
        btn_TrangChu_QLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TrangChu_QLNVActionPerformed(evt);
            }
        });

        btn_QLKH_QLNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_QLKH_QLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-user-40.png"))); // NOI18N
        btn_QLKH_QLNV.setText("    Quản lý khách hàng");
        btn_QLKH_QLNV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_QLKH_QLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLKH_QLNVActionPerformed(evt);
            }
        });

        btn_QLNV_QLNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_QLNV_QLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-manager-40.png"))); // NOI18N
        btn_QLNV_QLNV.setText("     Quản lý nhân viên");
        btn_QLNV_QLNV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_QLNV_QLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLNV_QLNVActionPerformed(evt);
            }
        });

        btn_QLSP_QLNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_QLSP_QLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-book-40.png"))); // NOI18N
        btn_QLSP_QLNV.setText("     Quản lý sản phẩm");
        btn_QLSP_QLNV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_QLSP_QLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLSP_QLNVActionPerformed(evt);
            }
        });

        btn_QLHD_QLNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_QLHD_QLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-file-invoice-dollar-40.png"))); // NOI18N
        btn_QLHD_QLNV.setText("     Quản lý hóa đơn");
        btn_QLHD_QLNV.setActionCommand(" Quản lý hóa đơn");
        btn_QLHD_QLNV.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_QLHD_QLNV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_QLHD_QLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLHD_QLNVActionPerformed(evt);
            }
        });

        btn_ThongKe_QLNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_ThongKe_QLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-analytics-40.png"))); // NOI18N
        btn_ThongKe_QLNV.setText("         Thống kê");
        btn_ThongKe_QLNV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_ThongKe_QLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThongKe_QLNVActionPerformed(evt);
            }
        });

        btn_TaiKhoan_QLNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_TaiKhoan_QLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-user-40_1.png"))); // NOI18N
        btn_TaiKhoan_QLNV.setText("         Tài khoản");
        btn_TaiKhoan_QLNV.setHideActionText(true);
        btn_TaiKhoan_QLNV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_TaiKhoan_QLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TaiKhoan_QLNVActionPerformed(evt);
            }
        });

        pn_TaiKhoan_Menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_Hinh_Menu.setText("Hình ");

        lbl_ChucVu_Menu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btn_DoiMK_Menu.setBackground(new java.awt.Color(102, 255, 102));
        btn_DoiMK_Menu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_DoiMK_Menu.setText("Đổi mật khẩu");
        btn_DoiMK_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DoiMK_MenuActionPerformed(evt);
            }
        });

        btn_DangXuat_Menu.setBackground(new java.awt.Color(102, 255, 102));
        btn_DangXuat_Menu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_DangXuat_Menu.setText("Đăng xuất");
        btn_DangXuat_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DangXuat_MenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_TaiKhoan_MenuLayout = new javax.swing.GroupLayout(pn_TaiKhoan_Menu);
        pn_TaiKhoan_Menu.setLayout(pn_TaiKhoan_MenuLayout);
        pn_TaiKhoan_MenuLayout.setHorizontalGroup(
            pn_TaiKhoan_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_TaiKhoan_MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Hinh_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_TaiKhoan_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_TenTaiKhoan_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_ChucVu_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_TaiKhoan_MenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_DoiMK_Menu)
                .addGap(34, 34, 34)
                .addComponent(btn_DangXuat_Menu)
                .addContainerGap())
        );
        pn_TaiKhoan_MenuLayout.setVerticalGroup(
            pn_TaiKhoan_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_TaiKhoan_MenuLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pn_TaiKhoan_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_Hinh_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pn_TaiKhoan_MenuLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbl_TenTaiKhoan_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_ChucVu_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_TaiKhoan_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_DoiMK_Menu)
                    .addComponent(btn_DangXuat_Menu))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pn_Menu_QLNVLayout = new javax.swing.GroupLayout(pn_Menu_QLNV);
        pn_Menu_QLNV.setLayout(pn_Menu_QLNVLayout);
        pn_Menu_QLNVLayout.setHorizontalGroup(
            pn_Menu_QLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_TrangChu_QLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_QLNV_QLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_QLSP_QLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_QLHD_QLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_ThongKe_QLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_TaiKhoan_QLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_QLKH_QLNV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_TaiKhoan_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_Menu_QLNVLayout.setVerticalGroup(
            pn_Menu_QLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_Menu_QLNVLayout.createSequentialGroup()
                .addComponent(btn_TrangChu_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_QLKH_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_QLNV_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_QLSP_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_QLHD_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ThongKe_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_TaiKhoan_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pn_TaiKhoan_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pn_Hinh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_Hinh.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_Hinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/trangchu.jpg"))); // NOI18N
        lbl_Hinh.setName(""); // NOI18N

        javax.swing.GroupLayout pn_HinhLayout = new javax.swing.GroupLayout(pn_Hinh);
        pn_Hinh.setLayout(pn_HinhLayout);
        pn_HinhLayout.setHorizontalGroup(
            pn_HinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Hinh, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        pn_HinhLayout.setVerticalGroup(
            pn_HinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Hinh, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pn_Menu_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_Hinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pn_TieuDe_QLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pn_TieuDe_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pn_Menu_QLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_Hinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_TrangChu_QLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TrangChu_QLNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_TrangChu_QLNVActionPerformed

    private void btn_QLKH_QLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLKH_QLNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_QLKH_QLNVActionPerformed

    private void btn_QLNV_QLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLNV_QLNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_QLNV_QLNVActionPerformed

    private void btn_QLSP_QLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLSP_QLNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_QLSP_QLNVActionPerformed

    private void btn_QLHD_QLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLHD_QLNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_QLHD_QLNVActionPerformed

    private void btn_ThongKe_QLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThongKe_QLNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ThongKe_QLNVActionPerformed

    private void btn_TaiKhoan_QLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TaiKhoan_QLNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_TaiKhoan_QLNVActionPerformed

    private void btn_DoiMK_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DoiMK_MenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_DoiMK_MenuActionPerformed

    private void btn_DangXuat_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DangXuat_MenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_DangXuat_MenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_DangXuat_Menu;
    private javax.swing.JButton btn_DoiMK_Menu;
    private javax.swing.JButton btn_QLHD_QLNV;
    private javax.swing.JButton btn_QLKH_QLNV;
    private javax.swing.JButton btn_QLNV_QLNV;
    private javax.swing.JButton btn_QLSP_QLNV;
    private javax.swing.JButton btn_TaiKhoan_QLNV;
    private javax.swing.JButton btn_ThongKe_QLNV;
    private javax.swing.JButton btn_TrangChu_QLNV;
    private javax.swing.JLabel lbl_ChucVu_Menu;
    private javax.swing.JLabel lbl_Hinh;
    private javax.swing.JLabel lbl_Hinh_Menu;
    private javax.swing.JLabel lbl_TenTaiKhoan_Menu;
    private javax.swing.JLabel lbl_TieuDe_QLNV;
    private javax.swing.JPanel pn_Hinh;
    private javax.swing.JPanel pn_Menu_QLNV;
    private javax.swing.JPanel pn_TaiKhoan_Menu;
    private javax.swing.JPanel pn_TieuDe_QLNV;
    // End of variables declaration//GEN-END:variables
}
