/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.quanlynhanvien.ui;

import com.mycompany.quanlynhanvien.Dao.NhaCungCapDao;
import com.mycompany.quanlynhanvien.Dao.NhanVienDao;
import com.mycompany.quanlynhanvien.Dao.NhomSanPhamDao;
import com.mycompany.quanlynhanvien.Dao.SanPhamDao;
import com.mycompany.quanlynhanvien.Dao.TacGiaDao;
import com.mycompany.quanlynhanvien.Helpers.ConnectDB;
import com.mycompany.quanlynhanvien.Helpers.DataValidator;
import com.mycompany.quanlynhanvien.Helpers.ImageHelper;
import com.mycompany.quanlynhanvien.Helpers.MessageDialogHelper;
import com.mycompany.quanlynhanvien.model.NhaCungCap;
import com.mycompany.quanlynhanvien.model.NhanVien;
import com.mycompany.quanlynhanvien.model.NhomSanPham;
import com.mycompany.quanlynhanvien.model.SanPham;
import com.mycompany.quanlynhanvien.model.TacGia;
import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.awt.Component;
import java.awt.HeadlessException;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.management.Query;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *
 * @author User
 */
public class QLSPForm extends javax.swing.JPanel {

    private DefaultTableModel tblModel;

    private byte[] personalImage;

    /**
     * Creates new form QLSPForm
     */
    public QLSPForm() {
        initComponents();
        initTable();
        loadDataToTable();
        resetTextFiled(txt_TenSP_QLSP);
        resetTextFiled(txt_MaSP_QLSP);
        resetTextFiled(txt_DonGia_QLSP);

        loadcbxNhomSP(cbx_ChonNhom_QLSP);
        loadcbxNhaCC(cbx_ChonNhaCungCap_QLSP);
        loadcbxTacGia(cbx_ChonTacGia_QLSP);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ThemSPForm = new javax.swing.JDialog();
        pn_TieuDe_TSP = new javax.swing.JPanel();
        lbl_Tieu_TSP = new javax.swing.JLabel();
        lbl_TieuDe_TSP = new javax.swing.JLabel();
        pn_ChucNang_TSP = new javax.swing.JPanel();
        btn_ThemSP_TSP = new javax.swing.JButton();
        btn_Huy_TSP = new javax.swing.JButton();
        lbl_NhaCC_TSP = new javax.swing.JLabel();
        lbl_NhomSP_TSP = new javax.swing.JLabel();
        lbl_SoLuong_TSP = new javax.swing.JLabel();
        lbl_DonGia_TSP = new javax.swing.JLabel();
        txt_TenSP_TSP = new javax.swing.JTextField();
        lbl_TenSP_TSP = new javax.swing.JLabel();
        txt_MaSP_TSP = new javax.swing.JTextField();
        lbl_MaSP_TSP = new javax.swing.JLabel();
        lbl_TacGia_TSP = new javax.swing.JLabel();
        cbx_NhaCC_TSP = new javax.swing.JComboBox<>();
        cbx_TacGia_TSP = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        lbl_HinhSP_TSP = new javax.swing.JLabel();
        lbl_Hinh_TSP = new javax.swing.JLabel();
        btn_ChonHinh_TSP = new javax.swing.JButton();
        txt_DonGia_TSP = new javax.swing.JTextField();
        cbx_NhomSP_TSP = new javax.swing.JComboBox<>();
        sn_SoLuong_TSP = new javax.swing.JSpinner();
        CapNhapSPForm = new javax.swing.JDialog();
        pn_TieuDe_CNSP = new javax.swing.JPanel();
        lbl_TieuCN = new javax.swing.JLabel();
        lbl_Tieu_CNSP = new javax.swing.JLabel();
        pn_ChucNang_CNSP = new javax.swing.JPanel();
        btn_CapNhap_CNSP = new javax.swing.JButton();
        btn_Huy_CNSP = new javax.swing.JButton();
        lbl_TacGia_CNSP = new javax.swing.JLabel();
        lbl_NhomSP_CNSP = new javax.swing.JLabel();
        lbl_SoLuong_CNSP = new javax.swing.JLabel();
        lbl_DonGia_CNSP = new javax.swing.JLabel();
        lbl_TenSP_CNSP = new javax.swing.JLabel();
        txt_TenSP_CNSP = new javax.swing.JTextField();
        txt_MaSP_CNSP = new javax.swing.JTextField();
        lbl_MaSP_CNSP = new javax.swing.JLabel();
        lbl_NhaCC_CNSP = new javax.swing.JLabel();
        cbx_TacGia_CNSP = new javax.swing.JComboBox<>();
        cbx_NhaCC_CNSP = new javax.swing.JComboBox<>();
        lbl_HinhSP_CNSP = new javax.swing.JLabel();
        lbl_Hinh_CNSP = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_ChonHinh_CNSP = new javax.swing.JButton();
        txt_DonGia_CNSP = new javax.swing.JTextField();
        sn_SoLuong_CNSP = new javax.swing.JSpinner();
        cbx_NhomSP_CNSP = new javax.swing.JComboBox<>();
        pn_TenForm_CNSP = new javax.swing.JPanel();
        lbl_TenForm_QLNV = new javax.swing.JLabel();
        pn_TTSP_QLSP = new javax.swing.JPanel();
        lbl_MaNV_QLSP = new javax.swing.JLabel();
        lbl_TenNV_QLSP = new javax.swing.JLabel();
        lbl_DonGia_QLSP = new javax.swing.JLabel();
        txt_DonGia_QLSP = new javax.swing.JTextField();
        txt_MaSP_QLSP = new javax.swing.JTextField();
        txt_TenSP_QLSP = new javax.swing.JTextField();
        lbl_NhomSP_QLSP = new javax.swing.JLabel();
        cbx_ChonNhom_QLSP = new javax.swing.JComboBox<>();
        lbl_NhaCC_QLSP = new javax.swing.JLabel();
        cbx_ChonNhaCungCap_QLSP = new javax.swing.JComboBox<>();
        lbl_TacGia_QLSP = new javax.swing.JLabel();
        cbx_ChonTacGia_QLSP = new javax.swing.JComboBox<>();
        scp_DanhSachSP_QLSP = new javax.swing.JScrollPane();
        tbl_DanhSachSP_QLSP = new javax.swing.JTable();
        pn_ChucNang_QLSP = new javax.swing.JPanel();
        btn_ThemSP_QLSP = new javax.swing.JButton();
        btn_Xoa_QLSP = new javax.swing.JButton();
        btn_CapNhap_QLSP = new javax.swing.JButton();
        btn_CapNhapBang_QLSP = new javax.swing.JButton();
        btn_TimKiem_TK_QLSP = new javax.swing.JButton();

        ThemSPForm.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        ThemSPForm.setLocation(new java.awt.Point(0, 0));
        ThemSPForm.setMinimumSize(new java.awt.Dimension(730, 500));
        ThemSPForm.setModal(true);
        ThemSPForm.setName("ThemSPForm"); // NOI18N

        pn_TieuDe_TSP.setBackground(new java.awt.Color(51, 255, 255));

        lbl_Tieu_TSP.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_Tieu_TSP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Tieu_TSP.setText("Trí Tuệ Việt");

        javax.swing.GroupLayout pn_TieuDe_TSPLayout = new javax.swing.GroupLayout(pn_TieuDe_TSP);
        pn_TieuDe_TSP.setLayout(pn_TieuDe_TSPLayout);
        pn_TieuDe_TSPLayout.setHorizontalGroup(
            pn_TieuDe_TSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Tieu_TSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_TieuDe_TSPLayout.setVerticalGroup(
            pn_TieuDe_TSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Tieu_TSP, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        lbl_TieuDe_TSP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_TieuDe_TSP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_TieuDe_TSP.setText("Nhập thông tin sản phẩm");
        lbl_TieuDe_TSP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pn_ChucNang_TSP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_ThemSP_TSP.setBackground(new java.awt.Color(51, 255, 51));
        btn_ThemSP_TSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_ThemSP_TSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-identification-documents-24.png"))); // NOI18N
        btn_ThemSP_TSP.setText("Thêm sản phẩm");
        btn_ThemSP_TSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemSP_TSPActionPerformed(evt);
            }
        });

        btn_Huy_TSP.setBackground(new java.awt.Color(51, 255, 51));
        btn_Huy_TSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Huy_TSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-unavailable-24.png"))); // NOI18N
        btn_Huy_TSP.setText("Hủy");
        btn_Huy_TSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Huy_TSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_ChucNang_TSPLayout = new javax.swing.GroupLayout(pn_ChucNang_TSP);
        pn_ChucNang_TSP.setLayout(pn_ChucNang_TSPLayout);
        pn_ChucNang_TSPLayout.setHorizontalGroup(
            pn_ChucNang_TSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_ChucNang_TSPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_ThemSP_TSP)
                .addGap(38, 38, 38)
                .addComponent(btn_Huy_TSP, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        pn_ChucNang_TSPLayout.setVerticalGroup(
            pn_ChucNang_TSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_ChucNang_TSPLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pn_ChucNang_TSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ThemSP_TSP)
                    .addComponent(btn_Huy_TSP))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        lbl_NhaCC_TSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_NhaCC_TSP.setText("Nhà cung cấp:");

        lbl_NhomSP_TSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_NhomSP_TSP.setText("Nhóm sản phẩm:");

        lbl_SoLuong_TSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_SoLuong_TSP.setText("Số lượng");

        lbl_DonGia_TSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_DonGia_TSP.setText("Đơn giá:");

        txt_TenSP_TSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbl_TenSP_TSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_TenSP_TSP.setText("Tên sản phẩm:");

        txt_MaSP_TSP.setEditable(false);
        txt_MaSP_TSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbl_MaSP_TSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_MaSP_TSP.setText("Mã sản phẩm:");

        lbl_TacGia_TSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_TacGia_TSP.setText("Tác Giả:");

        cbx_NhaCC_TSP.setEditable(true);
        cbx_NhaCC_TSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân viên bán hàng", "Quản lý" }));

        cbx_TacGia_TSP.setEditable(true);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lbl_HinhSP_TSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_HinhSP_TSP.setText("Hình sản phẩm");
        lbl_HinhSP_TSP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbl_Hinh_TSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_Hinh_TSP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Hinh_TSP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_ChonHinh_TSP.setBackground(new java.awt.Color(102, 255, 102));
        btn_ChonHinh_TSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_ChonHinh_TSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-imgur-24.png"))); // NOI18N
        btn_ChonHinh_TSP.setText("Chọn hình");
        btn_ChonHinh_TSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChonHinh_TSPActionPerformed(evt);
            }
        });

        txt_DonGia_TSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cbx_NhomSP_TSP.setEditable(true);
        cbx_NhomSP_TSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân viên bán hàng", "Quản lý" }));

        sn_SoLuong_TSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sn_SoLuong_TSP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout ThemSPFormLayout = new javax.swing.GroupLayout(ThemSPForm.getContentPane());
        ThemSPForm.getContentPane().setLayout(ThemSPFormLayout);
        ThemSPFormLayout.setHorizontalGroup(
            ThemSPFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_TieuDe_TSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_TieuDe_TSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_ChucNang_TSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ThemSPFormLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(ThemSPFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ThemSPFormLayout.createSequentialGroup()
                        .addGroup(ThemSPFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_NhomSP_TSP)
                            .addComponent(lbl_NhaCC_TSP))
                        .addGap(16, 16, 16)
                        .addGroup(ThemSPFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbx_NhomSP_TSP, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbx_NhaCC_TSP, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ThemSPFormLayout.createSequentialGroup()
                        .addGroup(ThemSPFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_SoLuong_TSP, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_MaSP_TSP, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_TenSP_TSP, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_DonGia_TSP, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ThemSPFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_TenSP_TSP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(txt_MaSP_TSP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(txt_DonGia_TSP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(sn_SoLuong_TSP))))
                .addGap(22, 22, 22)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(ThemSPFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ThemSPFormLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_TacGia_TSP, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbx_TacGia_TSP, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ThemSPFormLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(lbl_HinhSP_TSP))
                    .addGroup(ThemSPFormLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(ThemSPFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ThemSPFormLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(btn_ChonHinh_TSP))
                            .addComponent(lbl_Hinh_TSP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        ThemSPFormLayout.setVerticalGroup(
            ThemSPFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThemSPFormLayout.createSequentialGroup()
                .addComponent(pn_TieuDe_TSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_TieuDe_TSP, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ThemSPFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ThemSPFormLayout.createSequentialGroup()
                        .addGroup(ThemSPFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ThemSPFormLayout.createSequentialGroup()
                                .addGroup(ThemSPFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_MaSP_TSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_MaSP_TSP, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(ThemSPFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_TenSP_TSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_TenSP_TSP, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(ThemSPFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_DonGia_TSP, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_DonGia_TSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(ThemSPFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_SoLuong_TSP, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sn_SoLuong_TSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(ThemSPFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_NhomSP_TSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbx_NhomSP_TSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(ThemSPFormLayout.createSequentialGroup()
                                .addComponent(lbl_HinhSP_TSP)
                                .addGap(12, 12, 12)
                                .addComponent(lbl_Hinh_TSP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_ChonHinh_TSP)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(ThemSPFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_NhaCC_TSP, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbx_NhaCC_TSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_TacGia_TSP)
                            .addComponent(cbx_TacGia_TSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_ChucNang_TSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        CapNhapSPForm.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        CapNhapSPForm.setLocation(new java.awt.Point(0, 0));
        CapNhapSPForm.setMinimumSize(new java.awt.Dimension(747, 520));
        CapNhapSPForm.setModal(true);

        pn_TieuDe_CNSP.setBackground(new java.awt.Color(0, 255, 255));
        pn_TieuDe_CNSP.setForeground(new java.awt.Color(0, 255, 255));

        lbl_TieuCN.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_TieuCN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_TieuCN.setText("Trí Tuệ Việt");

        javax.swing.GroupLayout pn_TieuDe_CNSPLayout = new javax.swing.GroupLayout(pn_TieuDe_CNSP);
        pn_TieuDe_CNSP.setLayout(pn_TieuDe_CNSPLayout);
        pn_TieuDe_CNSPLayout.setHorizontalGroup(
            pn_TieuDe_CNSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_TieuCN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_TieuDe_CNSPLayout.setVerticalGroup(
            pn_TieuDe_CNSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_TieuCN, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        lbl_Tieu_CNSP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Tieu_CNSP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Tieu_CNSP.setText("Nhập thông tin sản phẩm");
        lbl_Tieu_CNSP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pn_ChucNang_CNSP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_CapNhap_CNSP.setBackground(new java.awt.Color(51, 255, 51));
        btn_CapNhap_CNSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_CapNhap_CNSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-identification-documents-24.png"))); // NOI18N
        btn_CapNhap_CNSP.setText("Cập nhập sản phẩm");
        btn_CapNhap_CNSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CapNhap_CNSPActionPerformed(evt);
            }
        });

        btn_Huy_CNSP.setBackground(new java.awt.Color(51, 255, 51));
        btn_Huy_CNSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Huy_CNSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-unavailable-24.png"))); // NOI18N
        btn_Huy_CNSP.setText("Hủy");
        btn_Huy_CNSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Huy_CNSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_ChucNang_CNSPLayout = new javax.swing.GroupLayout(pn_ChucNang_CNSP);
        pn_ChucNang_CNSP.setLayout(pn_ChucNang_CNSPLayout);
        pn_ChucNang_CNSPLayout.setHorizontalGroup(
            pn_ChucNang_CNSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_ChucNang_CNSPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_CapNhap_CNSP)
                .addGap(44, 44, 44)
                .addComponent(btn_Huy_CNSP, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        pn_ChucNang_CNSPLayout.setVerticalGroup(
            pn_ChucNang_CNSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_ChucNang_CNSPLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(pn_ChucNang_CNSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_CapNhap_CNSP)
                    .addComponent(btn_Huy_CNSP))
                .addGap(20, 20, 20))
        );

        lbl_TacGia_CNSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_TacGia_CNSP.setText("Tác giả:");

        lbl_NhomSP_CNSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_NhomSP_CNSP.setText("Nhóm sản phẩm:");

        lbl_SoLuong_CNSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_SoLuong_CNSP.setText("Số lượng:");

        lbl_DonGia_CNSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_DonGia_CNSP.setText("Đơn giá:");

        lbl_TenSP_CNSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_TenSP_CNSP.setText("Tên sản phẩm:");

        txt_TenSP_CNSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_TenSP_CNSP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_TenSP_CNSPFocusLost(evt);
            }
        });

        txt_MaSP_CNSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_MaSP_CNSP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_MaSP_CNSPFocusLost(evt);
            }
        });
        txt_MaSP_CNSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_MaSP_CNSPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_MaSP_CNSPMouseExited(evt);
            }
        });

        lbl_MaSP_CNSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_MaSP_CNSP.setText("Mã sản phẩm:");

        lbl_NhaCC_CNSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_NhaCC_CNSP.setText("Nhà cung cấp:");

        cbx_TacGia_CNSP.setEditable(true);
        cbx_TacGia_CNSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân viên bán hàng", "Quản lý" }));

        cbx_NhaCC_CNSP.setEditable(true);

        lbl_HinhSP_CNSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_HinhSP_CNSP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_HinhSP_CNSP.setText("Hình sản phẩm");

        lbl_Hinh_CNSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_Hinh_CNSP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Hinh_CNSP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btn_ChonHinh_CNSP.setBackground(new java.awt.Color(102, 255, 102));
        btn_ChonHinh_CNSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_ChonHinh_CNSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-imgur-24.png"))); // NOI18N
        btn_ChonHinh_CNSP.setText("Chọn hình");
        btn_ChonHinh_CNSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChonHinh_CNSPActionPerformed(evt);
            }
        });

        txt_DonGia_CNSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_DonGia_CNSP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_DonGia_CNSPFocusLost(evt);
            }
        });

        sn_SoLuong_CNSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cbx_NhomSP_CNSP.setEditable(true);

        javax.swing.GroupLayout CapNhapSPFormLayout = new javax.swing.GroupLayout(CapNhapSPForm.getContentPane());
        CapNhapSPForm.getContentPane().setLayout(CapNhapSPFormLayout);
        CapNhapSPFormLayout.setHorizontalGroup(
            CapNhapSPFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CapNhapSPFormLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(CapNhapSPFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CapNhapSPFormLayout.createSequentialGroup()
                        .addComponent(lbl_NhaCC_CNSP)
                        .addGap(28, 28, 28)
                        .addComponent(cbx_NhaCC_CNSP, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CapNhapSPFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(CapNhapSPFormLayout.createSequentialGroup()
                            .addComponent(lbl_NhomSP_CNSP)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cbx_NhomSP_CNSP, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(CapNhapSPFormLayout.createSequentialGroup()
                            .addGroup(CapNhapSPFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_SoLuong_CNSP, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_DonGia_CNSP, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_TenSP_CNSP)
                                .addComponent(lbl_MaSP_CNSP))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(CapNhapSPFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(CapNhapSPFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_TenSP_CNSP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                    .addComponent(txt_MaSP_CNSP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                    .addComponent(txt_DonGia_CNSP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                                .addComponent(sn_SoLuong_CNSP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(CapNhapSPFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CapNhapSPFormLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(lbl_HinhSP_CNSP))
                    .addGroup(CapNhapSPFormLayout.createSequentialGroup()
                        .addComponent(lbl_TacGia_CNSP, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(CapNhapSPFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbx_TacGia_CNSP, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CapNhapSPFormLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(btn_ChonHinh_CNSP))
                            .addComponent(lbl_Hinh_CNSP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
            .addComponent(pn_TieuDe_CNSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_ChucNang_CNSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_Tieu_CNSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        CapNhapSPFormLayout.setVerticalGroup(
            CapNhapSPFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CapNhapSPFormLayout.createSequentialGroup()
                .addComponent(pn_TieuDe_CNSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Tieu_CNSP, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CapNhapSPFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CapNhapSPFormLayout.createSequentialGroup()
                        .addGroup(CapNhapSPFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CapNhapSPFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_MaSP_CNSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_MaSP_CNSP, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_HinhSP_CNSP, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(CapNhapSPFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CapNhapSPFormLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(CapNhapSPFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_TenSP_CNSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_TenSP_CNSP, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(CapNhapSPFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_DonGia_CNSP, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_DonGia_CNSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(CapNhapSPFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_SoLuong_CNSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sn_SoLuong_CNSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(CapNhapSPFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_NhomSP_CNSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbx_NhomSP_CNSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(CapNhapSPFormLayout.createSequentialGroup()
                                .addComponent(lbl_Hinh_CNSP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(btn_ChonHinh_CNSP)))
                        .addGap(18, 18, 18)
                        .addGroup(CapNhapSPFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(CapNhapSPFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl_NhaCC_CNSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbx_NhaCC_CNSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbx_TacGia_CNSP)
                            .addComponent(lbl_TacGia_CNSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_ChucNang_CNSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setPreferredSize(new java.awt.Dimension(1341, 743));

        lbl_TenForm_QLNV.setBackground(new java.awt.Color(255, 255, 255));
        lbl_TenForm_QLNV.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_TenForm_QLNV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_TenForm_QLNV.setText("Quản Lý Sản Phẩm");
        lbl_TenForm_QLNV.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout pn_TenForm_CNSPLayout = new javax.swing.GroupLayout(pn_TenForm_CNSP);
        pn_TenForm_CNSP.setLayout(pn_TenForm_CNSPLayout);
        pn_TenForm_CNSPLayout.setHorizontalGroup(
            pn_TenForm_CNSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_TenForm_CNSPLayout.createSequentialGroup()
                .addComponent(lbl_TenForm_QLNV, javax.swing.GroupLayout.DEFAULT_SIZE, 1290, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_TenForm_CNSPLayout.setVerticalGroup(
            pn_TenForm_CNSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_TenForm_QLNV, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        pn_TTSP_QLSP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        pn_TTSP_QLSP.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pn_TTSP_QLSPMouseMoved(evt);
            }
        });

        lbl_MaNV_QLSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_MaNV_QLSP.setText("Mã sản phẩm:");

        lbl_TenNV_QLSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_TenNV_QLSP.setText("Tên sản phẩm:");

        lbl_DonGia_QLSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_DonGia_QLSP.setText("Đơn giá:");

        txt_DonGia_QLSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_DonGia_QLSP.setMinimumSize(new java.awt.Dimension(7, 25));
        txt_DonGia_QLSP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_DonGia_QLSPFocusGained(evt);
            }
        });
        txt_DonGia_QLSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DonGia_QLSPActionPerformed(evt);
            }
        });

        txt_MaSP_QLSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_MaSP_QLSP.setMinimumSize(new java.awt.Dimension(7, 25));
        txt_MaSP_QLSP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_MaSP_QLSPFocusGained(evt);
            }
        });
        txt_MaSP_QLSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_MaSP_QLSPMouseExited(evt);
            }
        });

        txt_TenSP_QLSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_TenSP_QLSP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_TenSP_QLSPFocusGained(evt);
            }
        });

        lbl_NhomSP_QLSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_NhomSP_QLSP.setText("Nhóm sản phẩm:");

        cbx_ChonNhom_QLSP.setEditable(true);
        cbx_ChonNhom_QLSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbx_ChonNhom_QLSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn nhóm", "1", "2", "3" }));
        cbx_ChonNhom_QLSP.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cbx_ChonNhom_QLSPMouseMoved(evt);
            }
        });
        cbx_ChonNhom_QLSP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbx_ChonNhom_QLSPFocusGained(evt);
            }
        });
        cbx_ChonNhom_QLSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbx_ChonNhom_QLSPMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cbx_ChonNhom_QLSPMouseExited(evt);
            }
        });

        lbl_NhaCC_QLSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_NhaCC_QLSP.setText("Nhà cung cấp:");

        cbx_ChonNhaCungCap_QLSP.setEditable(true);
        cbx_ChonNhaCungCap_QLSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbx_ChonNhaCungCap_QLSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn nhà cung cấp", "1", "2", "3" }));
        cbx_ChonNhaCungCap_QLSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cbx_ChonNhaCungCap_QLSPMouseExited(evt);
            }
        });

        lbl_TacGia_QLSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_TacGia_QLSP.setText("Tác giả:");

        cbx_ChonTacGia_QLSP.setEditable(true);
        cbx_ChonTacGia_QLSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbx_ChonTacGia_QLSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn tác giả", "1", "2", "3" }));
        cbx_ChonTacGia_QLSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cbx_ChonTacGia_QLSPMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_TTSP_QLSPLayout = new javax.swing.GroupLayout(pn_TTSP_QLSP);
        pn_TTSP_QLSP.setLayout(pn_TTSP_QLSPLayout);
        pn_TTSP_QLSPLayout.setHorizontalGroup(
            pn_TTSP_QLSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_TTSP_QLSPLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(pn_TTSP_QLSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pn_TTSP_QLSPLayout.createSequentialGroup()
                        .addGroup(pn_TTSP_QLSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_TenNV_QLSP)
                            .addComponent(lbl_DonGia_QLSP, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(pn_TTSP_QLSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_DonGia_QLSP, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                            .addComponent(txt_TenSP_QLSP)))
                    .addGroup(pn_TTSP_QLSPLayout.createSequentialGroup()
                        .addComponent(lbl_MaNV_QLSP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(txt_MaSP_QLSP, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(215, 215, 215)
                .addGroup(pn_TTSP_QLSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_NhaCC_QLSP)
                    .addComponent(lbl_NhomSP_QLSP)
                    .addComponent(lbl_TacGia_QLSP))
                .addGap(27, 27, 27)
                .addGroup(pn_TTSP_QLSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbx_ChonTacGia_QLSP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbx_ChonNhaCungCap_QLSP, 0, 200, Short.MAX_VALUE)
                    .addComponent(cbx_ChonNhom_QLSP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_TTSP_QLSPLayout.setVerticalGroup(
            pn_TTSP_QLSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_TTSP_QLSPLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pn_TTSP_QLSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_MaNV_QLSP)
                    .addComponent(txt_MaSP_QLSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_NhomSP_QLSP)
                    .addComponent(cbx_ChonNhom_QLSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(pn_TTSP_QLSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_TenSP_QLSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_TenNV_QLSP)
                    .addComponent(lbl_NhaCC_QLSP)
                    .addComponent(cbx_ChonNhaCungCap_QLSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pn_TTSP_QLSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_DonGia_QLSP)
                    .addComponent(txt_DonGia_QLSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_TacGia_QLSP)
                    .addComponent(cbx_ChonTacGia_QLSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(150, 150, 150))
        );

        tbl_DanhSachSP_QLSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbl_DanhSachSP_QLSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã NV", "Tên Nhân Viên", "Giới tính", "Ngày sinh", "Số điện thoại", "Chức vụ", "Tình trạng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_DanhSachSP_QLSP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbl_DanhSachSP_QLSP.setName("Danh sách nhân viên\n"); // NOI18N
        tbl_DanhSachSP_QLSP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tbl_DanhSachSP_QLSPFocusLost(evt);
            }
        });
        tbl_DanhSachSP_QLSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_DanhSachSP_QLSPMouseClicked(evt);
            }
        });
        scp_DanhSachSP_QLSP.setViewportView(tbl_DanhSachSP_QLSP);

        btn_ThemSP_QLSP.setBackground(new java.awt.Color(51, 255, 51));
        btn_ThemSP_QLSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_ThemSP_QLSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-identification-documents-24.png"))); // NOI18N
        btn_ThemSP_QLSP.setText("Thêm sản phẩm");
        btn_ThemSP_QLSP.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_ThemSP_QLSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemSP_QLSPActionPerformed(evt);
            }
        });

        btn_Xoa_QLSP.setBackground(new java.awt.Color(51, 255, 51));
        btn_Xoa_QLSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Xoa_QLSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-user-24.png"))); // NOI18N
        btn_Xoa_QLSP.setText("-  Xóa sản phẩm");
        btn_Xoa_QLSP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Xoa_QLSP.setMinimumSize(new java.awt.Dimension(93, 25));
        btn_Xoa_QLSP.setPreferredSize(new java.awt.Dimension(93, 25));
        btn_Xoa_QLSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Xoa_QLSPActionPerformed(evt);
            }
        });

        btn_CapNhap_QLSP.setBackground(new java.awt.Color(102, 255, 102));
        btn_CapNhap_QLSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_CapNhap_QLSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-pencil-24.png"))); // NOI18N
        btn_CapNhap_QLSP.setText("Cập nhập sản phẩm");
        btn_CapNhap_QLSP.setFocusable(false);
        btn_CapNhap_QLSP.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_CapNhap_QLSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CapNhap_QLSPActionPerformed(evt);
            }
        });

        btn_CapNhapBang_QLSP.setBackground(new java.awt.Color(51, 255, 51));
        btn_CapNhapBang_QLSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_CapNhapBang_QLSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-easel-24.png"))); // NOI18N
        btn_CapNhapBang_QLSP.setText("Cập nhập lại bảng");
        btn_CapNhapBang_QLSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CapNhapBang_QLSPActionPerformed(evt);
            }
        });

        btn_TimKiem_TK_QLSP.setBackground(new java.awt.Color(51, 255, 51));
        btn_TimKiem_TK_QLSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_TimKiem_TK_QLSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-search-24.png"))); // NOI18N
        btn_TimKiem_TK_QLSP.setText("Tìm kiếm");
        btn_TimKiem_TK_QLSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiem_TK_QLSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_ChucNang_QLSPLayout = new javax.swing.GroupLayout(pn_ChucNang_QLSP);
        pn_ChucNang_QLSP.setLayout(pn_ChucNang_QLSPLayout);
        pn_ChucNang_QLSPLayout.setHorizontalGroup(
            pn_ChucNang_QLSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_ChucNang_QLSPLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(btn_TimKiem_TK_QLSP, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(btn_ThemSP_QLSP)
                .addGap(92, 92, 92)
                .addComponent(btn_Xoa_QLSP, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(btn_CapNhap_QLSP)
                .addGap(68, 68, 68)
                .addComponent(btn_CapNhapBang_QLSP)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        pn_ChucNang_QLSPLayout.setVerticalGroup(
            pn_ChucNang_QLSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_ChucNang_QLSPLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(pn_ChucNang_QLSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_CapNhap_QLSP, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_CapNhapBang_QLSP, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ThemSP_QLSP, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Xoa_QLSP, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_TimKiem_TK_QLSP, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_TenForm_CNSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(scp_DanhSachSP_QLSP, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pn_ChucNang_QLSP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pn_TTSP_QLSP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pn_TenForm_CNSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_TTSP_QLSP, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_ChucNang_QLSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scp_DanhSachSP_QLSP, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void initTable() {

        tblModel = new DefaultTableModel(){

   @Override
   public boolean isCellEditable(int row, int column) {
       //Only the third column
       return column == -1;
   }
};
        tblModel.setColumnIdentifiers(new String[]{"Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Đơn giá", "Mã nhóm sản phẩm", "Mã nhà cung cấp", "Mã tác giả", "Hình sản phẩm"});
        tbl_DanhSachSP_QLSP.setModel(tblModel);
        tbl_DanhSachSP_QLSP.getColumn("Hình sản phẩm").setCellRenderer(new myTableCellRenderer());
    }

    private void resetTable() {
        tblModel.setRowCount(0);
        loadDataToTable();
    }

    private void loadcbxNhomSP(JComboBox<String> cbx) {
        cbx.setBackground(Color.white);
        try {
            NhomSanPhamDao dao = new NhomSanPhamDao();
            List<NhomSanPham> list = dao.findAll();
            cbx.removeAllItems();
            cbx.addItem("Chọn nhóm sản phẩm");
            for (NhomSanPham it : list) {
                cbx.addItem(it.getMaNhomSP().replaceAll("\\s", "") + "-" + it.getTenNhomSP());

            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(null, e.getMessage(), "Lỗi");

        }//To change body of generated methods, choose Tools | Templates.
    }

    class myTableCellRenderer implements TableCellRenderer {

        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            TableColumn tb = tbl_DanhSachSP_QLSP.getColumn("Hình sản phẩm");
            tb.setMaxWidth(150);
            tb.setMinWidth(150);
            tbl_DanhSachSP_QLSP.setRowHeight(150);
            return (Component) value;
        }
    }

    private void resetTextFiled(JDateChooser field) {
        field.setDate(null);
        field.setBackground(Color.white);//To change body of generated methods, choose Tools | Templates.
    }

    private void resetTextFiled(JTextField field) throws HeadlessException {
        field.setText("");
        field.setBackground(Color.white);
    }

    private void resetTextFiled(JSpinner field) {
        field.setValue(0);
        field.setBackground(Color.white);//To change body of generated methods, choose Tools | Templates.
    }

    public String tuDongLayMa() {
        String maSP = "";
        try {
            Connection con = ConnectDB.getInstance().getConnection();
            String sql = " DECLARE @ID VARCHAR(5)\r\n"
                    + " IF (SELECT COUNT(maSP) FROM SanPham) = 0\r\n"
                    + " SET @ID = '0'\r\n"
                    + " ELSE\r\n"
                    + " SELECT @ID = MAX(RIGHT(rtrim(maSP), 3)) FROM SanPham\r\n"
                    + " SELECT @ID = CASE\r\n"
                    + " WHEN @ID >= 0 and @ID < 9 THEN 'SP00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)\r\n"
                    + " WHEN @ID >= 9 THEN 'SP0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)\r\n"
                    + " END\r\n"
                    + " select @ID";

            Statement statement = con.createStatement();
            ResultSet rs = statement.executeQuery(sql);
            while (rs.next()) {
                String ID = rs.getString(1);
                maSP = ID;
            }
        } catch (SQLException e) {
            // TODO: handle exception
            e.printStackTrace();
        }
        return maSP;
    }

    private void resetThongTinThemSPForm() throws HeadlessException {
        resetTextFiled(txt_TenSP_TSP);
        resetTextFiled(sn_SoLuong_TSP);
        resetTextFiled(txt_DonGia_TSP);
        txt_MaSP_TSP.setText(tuDongLayMa());

        loadcbxNhomSP(cbx_NhomSP_TSP);
        loadcbxNhaCC(cbx_NhaCC_TSP);
        loadcbxTacGia(cbx_TacGia_TSP);

    }

    public void loadcbxNhaCC(JComboBox<String> cbx) {
        cbx.setBackground(Color.white);
        try {
            NhaCungCapDao dao = new NhaCungCapDao();
            List<NhaCungCap> list = dao.findAll();
            cbx.removeAllItems();
            cbx.addItem("Chọn nhà cung cấp");

            for (NhaCungCap it : list) {

                cbx.addItem(it.getMaNhaCC().replaceAll("\\s", "") + "-" + it.getTenNhaCC());

            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(null, e.getMessage(), "Lỗi");

        }
    }

    public void loadcbxTacGia(JComboBox<String> cbx) {
        cbx.setBackground(Color.white);
        try {
            TacGiaDao dao = new TacGiaDao();
            List<TacGia> list = dao.findAll();
            cbx.removeAllItems();
            cbx.addItem("Chọn tác giả");
            for (TacGia it : list) {
                cbx.addItem(it.getMaTacGia().replaceAll("\\s", "") + "-" + it.getTenTacGia());

            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(null, e.getMessage(), "Lỗi");

        }
    }

    private void loadDataToTable() {
        try {
            SanPhamDao dao = new SanPhamDao();
            List<SanPham> list = dao.findAll();
            tblModel.setRowCount(0);
            for (SanPham it : list) {
                JLabel lbl = new JLabel();
                //MessageDialogHelper.showMessageDialog(null, it.getTinhTrang(), "Thông báo");
                ImageIcon icon = new ImageIcon();
                if (it.getHinhSP() != null) {
                    //Image img = ImageHelper.CreateImageFromByteArray(nv.getHinh(), "jpg");
                    //lbl_Hinh_CN.setIcon(new ImageIcon(img));
                    //personalImage = nv.getHinh();

                    icon = new ImageIcon(it.getHinhSP());
                    lbl.setIcon(icon);
                } else {
                    // personalImage = nv.getHinh();
                    //ImageIcon icon = new ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/Screenshot 2021-11-17 090047.jpg")); 
                    // lbl_Hinh_CN.setIcon(icon);
                    icon = new ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/Screenshot 2021-11-17 090047.jpg"));
                    lbl.setIcon(icon);

                }

                tblModel.addRow(new Object[]{it.getMaSP(), it.getTenSP(), it.getSoLuong(), it.getDonGia(), it.getNhomSanPham().getMaNhomSP(), it.getNhaCungCap().getMaNhaCC(), it.getTacGia().getMaTacGia(), lbl});

                tblModel.fireTableDataChanged();
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(null, e.getMessage(), "Lỗi");

        }
    }

    private void restartFormCapNhap() throws HeadlessException {
        resetTextFiled(txt_MaSP_CNSP);
        resetTextFiled(txt_TenSP_CNSP);
        resetTextFiled(txt_DonGia_CNSP);
        resetTextFiled(sn_SoLuong_CNSP);
        //resetTextFiled(txt_ChucVu_CN);
        loadcbxNhomSP(cbx_NhomSP_CNSP);
        loadcbxNhaCC(cbx_NhaCC_CNSP);
        loadcbxTacGia(cbx_TacGia_CNSP);
        //String id = (String) tbl_DanhSachNV_QLNV.getValueAt(tbl_DanhSachNV_QLNV.getSelectedRow(), 7);
        NhapTTCapNhapTTable();
        //loadcbxmaTK_CN();
    }

    private void NhapTTCapNhapTTable() throws HeadlessException {

        try {
            int row = tbl_DanhSachSP_QLSP.getSelectedRow();
            //MessageDialogHelper.showConfirmDialog(null, ""+row, "Cảnh báo");
            if (row >= 0) {
                String id = (String) tbl_DanhSachSP_QLSP.getValueAt(row, 0);
                SanPhamDao dao = new SanPhamDao();
                SanPham sp = dao.find(id);

                if (sp != null) {
                    txt_MaSP_CNSP.setText(sp.getMaSP().replaceAll("\\s", ""));
                    txt_TenSP_CNSP.setText(sp.getTenSP());
                    String donGia = String.valueOf(sp.getDonGia());
                    txt_DonGia_CNSP.setText(donGia.replaceAll("\\s", ""));
                    sn_SoLuong_CNSP.setValue(sp.getSoLuong());

                    cbx_NhomSP_CNSP.setSelectedItem(sp.getNhomSanPham().getMaNhomSP().replaceAll("\\s", "") + "-" + sp.getNhomSanPham().getTenNhomSP());
                    cbx_NhaCC_CNSP.setSelectedItem(sp.getNhaCungCap().getMaNhaCC().replaceAll("\\s", "") + "-" + sp.getNhaCungCap().getTenNhaCC());
                    cbx_TacGia_CNSP.setSelectedItem(sp.getTacGia().getMaTacGia().replaceAll("\\s", "") + "-" + sp.getTacGia().getTenTacGia());

                    if (sp.getHinhSP() != null) {
                        Image img = ImageHelper.CreateImageFromByteArray(sp.getHinhSP(), "jpg");
                        lbl_Hinh_CNSP.setIcon(new ImageIcon(img));
                        personalImage = sp.getHinhSP();

                    } else {
                        personalImage = sp.getHinhSP();
                        ImageIcon icon = new ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/Screenshot 2021-11-17 090047.jpg"));
                        lbl_Hinh_CNSP.setIcon(icon);
                    }
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getStackTrace(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }

    }
    private void txt_DonGia_QLSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DonGia_QLSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DonGia_QLSPActionPerformed

    private void tbl_DanhSachSP_QLSPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbl_DanhSachSP_QLSPFocusLost

    }//GEN-LAST:event_tbl_DanhSachSP_QLSPFocusLost

    private void tbl_DanhSachSP_QLSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_DanhSachSP_QLSPMouseClicked
        try {
            int row = tbl_DanhSachSP_QLSP.getSelectedRow();
            //MessageDialogHelper.showConfirmDialog(null, ""+row, "Cảnh báo");
            if (row >= 0) {
                String id = (String) tbl_DanhSachSP_QLSP.getValueAt(row, 0);
                SanPhamDao dao = new SanPhamDao();
                SanPham nv = dao.find(id);

                /* if(nv!=null)
                {

                    if(nv.getHinh()!=null)
                    {
                        Image img = ImageHelper.CreateImageFromByteArray(nv.getHinh(), "jpg");
                        lbl_Hinh_QLSP.setIcon(new ImageIcon(img));
                        personalImage = nv.getHinh();

                    }else{
                        personalImage = nv.getHinh();
                        ImageIcon icon = new ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/Screenshot 2021-11-17 090047.jpg"));
                        lbl_Hinh_QLSP.setIcon(icon);}}*/
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getStackTrace(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tbl_DanhSachSP_QLSPMouseClicked

    private void btn_ThemSP_QLSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemSP_QLSPActionPerformed
        personalImage = null;
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/Screenshot 2021-11-17 090047.jpg"));
        lbl_Hinh_TSP.setIcon(icon);
        resetThongTinThemSPForm();

        ThemSPForm.setLocationRelativeTo(null);
        ThemSPForm.setVisible(true);


    }//GEN-LAST:event_btn_ThemSP_QLSPActionPerformed

    private void btn_Xoa_QLSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Xoa_QLSPActionPerformed
        //StringBuilder sb = new StringBuilder();
        //Kiểm tra có chọn trong table
        String maSanPham = "";
        try {
            int row = tbl_DanhSachSP_QLSP.getSelectedRow();

            if (row >= 0) {
                String id = (String) tblModel.getValueAt(row, 0);
                maSanPham = JOptionPane.showInputDialog("Nhập mã sản phẩm muốn xóa", id);
            } else {
                maSanPham = JOptionPane.showInputDialog("Nhập mã sản phẩm muốn xóa");
            }
        } catch (Exception e) {
        }
        //Xóa nhân viên

        //JOptionPane.showMessageDialog(null, maSanPham==null);
        if ((maSanPham == null) == false) {
            if (maSanPham.equals("") == false) {
                if (MessageDialogHelper.showConfirmDialog(null, "Bạn có muốn xóa sản phẩm không?", "Hỏi") == JOptionPane.YES_OPTION) {
                } else {
                    return;
                }
                try {

                    SanPhamDao dao = new SanPhamDao();

                    if (dao.delete(maSanPham)) {

                        MessageDialogHelper.showMessageDialog(null, "Xóa sản phẩm thành công", "Thông báo");
                        resetTable();
                    } else {
                        MessageDialogHelper.showConfirmDialog(null, "Xóa sản phẩm không được do lỗi", "Cảnh báo");
                    }

                } catch (Exception e) {
                    e.printStackTrace();
                    MessageDialogHelper.showErrorDialog(null, e.getMessage(),
                             "Lỗi");
                }
            }
        }
    }//GEN-LAST:event_btn_Xoa_QLSPActionPerformed

    private void btn_CapNhap_QLSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CapNhap_QLSPActionPerformed
        personalImage = null;
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/Screenshot 2021-11-17 090047.jpg"));
        lbl_Hinh_CNSP.setIcon(icon);
        restartFormCapNhap();
        CapNhapSPForm.setLocationRelativeTo(null);
        CapNhapSPForm.setVisible(true);
    }//GEN-LAST:event_btn_CapNhap_QLSPActionPerformed

    private void btn_TimKiem_TK_QLSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiem_TK_QLSPActionPerformed
        try {

            StringBuilder sb = new StringBuilder();
            //MessageDialogHelper.showMessageDialog(null, (String) cbx_MaTK_T.getSelectedItem(), "Thông báo");
            DataValidator.validateEmptyMaSP_TK(txt_MaSP_QLSP, sb);
            DataValidator.validateEmptyTen_TK(txt_TenSP_QLSP, sb);
            DataValidator.validateEmptyDonGia_TK(txt_DonGia_QLSP, sb);

            //DataValidator.validateEmptyChucVu(txt_ChucVu_T, sb);
            if (sb.length() > 0) {
                MessageDialogHelper.showErrorDialog(null, sb.toString(), "Lỗi");
                return;
            }
            SanPhamDao dao = new SanPhamDao();
            NhomSanPhamDao daoNSP = new NhomSanPhamDao();
            NhaCungCapDao daoNCC = new NhaCungCapDao();
            TacGiaDao daoTG = new TacGiaDao();
            //

            //
            String[] NSP = cbx_ChonNhom_QLSP.getSelectedItem().toString().split("-");
            NhomSanPham textNSP = daoNSP.findMaNhomSPByTen(NSP[0]);
            String maNSP = "";
            if (!(NSP[0].equals("Chọn nhóm sản phẩm")||NSP[0].replaceAll("\\s", "").equals(""))) {
                if (textNSP != null) {
                    maNSP = textNSP.getMaNhomSP();
                } else {
                    MessageDialogHelper.showMessageDialog(null, "Nhóm sản phẩm không tồn tại", "Thông báo");
                    return;
                }
            }
            //
            String[] NCC = cbx_ChonNhaCungCap_QLSP.getSelectedItem().toString().split("-");
            NhaCungCap textNCC = daoNCC.findMaNhaCCByTen(NCC[0]);
            String maNCC = "";
            if (!!(NCC[0].equals("Chọn nhà cung cấp")||NCC[0].replaceAll("\\s", "").equals(""))) {
                if (textNCC != null) {
                    maNCC = textNCC.getMaNhaCC();
                } else {
                    MessageDialogHelper.showMessageDialog(null, "Nhà cung cấp không tồn tại", "Thông báo");
                    return;
                }
            }

            //
            String[] TG = cbx_ChonTacGia_QLSP.getSelectedItem().toString().split("-");
            TacGia textTG = daoTG.findMaTacGiaByTen(TG[0]);
            String maTG = "";
            if (!!(TG[0].equals("Chọn tác giả")||TG[0].replaceAll("\\s", "").equals(""))) {
                if (textTG != null) {
                    maTG = textTG.getMaTacGia();
                } else {
                    MessageDialogHelper.showMessageDialog(null, "Tác giả không tồn tại", "Thông báo");
                    return;
                }
            }
            //JOptionPane.showConfirmDialog(null, maNSP);
            List<SanPham> list = dao.findDK(txt_MaSP_QLSP.getText(), txt_TenSP_QLSP.getText(), txt_DonGia_QLSP.getText(), maNSP, maNCC, maTG);

            tblModel.setRowCount(0);
            for (SanPham it : list) {
                JLabel lbl = new JLabel();
                //MessageDialogHelper.showMessageDialog(null, it.getTinhTrang(), "Thông báo");
                ImageIcon icon = new ImageIcon();
                if (it.getHinhSP() != null) {
                    //Image img = ImageHelper.CreateImageFromByteArray(nv.getHinh(), "jpg");
                    //lbl_Hinh_CN.setIcon(new ImageIcon(img));
                    //personalImage = nv.getHinh();

                    icon = new ImageIcon(it.getHinhSP());
                    lbl.setIcon(icon);
                } else {
                    // personalImage = nv.getHinh();
                    //ImageIcon icon = new ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/Screenshot 2021-11-17 090047.jpg")); 
                    // lbl_Hinh_CN.setIcon(icon);
                    icon = new ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/Screenshot 2021-11-17 090047.jpg"));
                    lbl.setIcon(icon);

                }

                tblModel.addRow(new Object[]{it.getMaSP(), it.getTenSP(), it.getSoLuong(), it.getDonGia(), it.getNhomSanPham().getMaNhomSP(), it.getNhaCungCap().getMaNhaCC(), it.getTacGia().getMaTacGia(), lbl});

                tblModel.fireTableDataChanged();
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(null, e.getMessage(), "Lỗi");

        }
    }//GEN-LAST:event_btn_TimKiem_TK_QLSPActionPerformed

    private void btn_CapNhapBang_QLSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CapNhapBang_QLSPActionPerformed
        personalImage = null;

        resetTable();
        loadcbxNhaCC(cbx_ChonNhaCungCap_QLSP);
        loadcbxTacGia(cbx_ChonTacGia_QLSP);
        loadcbxNhomSP(cbx_ChonNhom_QLSP);


    }//GEN-LAST:event_btn_CapNhapBang_QLSPActionPerformed

    private void btn_ThemSP_TSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemSP_TSPActionPerformed
        StringBuilder sb = new StringBuilder();
        //MessageDialogHelper.showMessageDialog(null, (String) cbx_MaTK_T.getSelectedItem(), "Thông báo");
        DataValidator.validateEmptyTenNV(txt_TenSP_TSP, sb);
        DataValidator.validateEmptyDonGia(txt_DonGia_TSP, sb);
        DataValidator.validateEmptySoLuong(sn_SoLuong_TSP, sb);
        DataValidator.validateEmptyCBXNhomSP(cbx_NhomSP_TSP, sb);
        DataValidator.validateEmptyCBXNhaCC(cbx_NhaCC_TSP, sb);
        DataValidator.validateEmptyCBXTacGia(cbx_TacGia_TSP, sb);

        //DataValidator.validateEmptyChucVu(txt_ChucVu_T, sb);
        if (sb.length() > 0) {
            MessageDialogHelper.showErrorDialog(null, sb.toString(), "Lỗi");
            return;
        }

        try {
            SanPham sp = new SanPham();

            //
            String[] maNSP = cbx_NhomSP_TSP.getSelectedItem().toString().split("-");
            NhomSanPhamDao daoNSP = new NhomSanPhamDao();
            NhomSanPham NSP = new NhomSanPham();
            NSP = daoNSP.findMaNhomSPByTen(maNSP[0]);
            if (NSP != null) {

                sp.setNhomSanPham(NSP);
            } else {
                cbx_NhomSP_TSP.setBackground(Color.red);
                MessageDialogHelper.showErrorDialog(null, " Nhóm sản phẩm không tồn tại, vui lòng nhập lại", "LỖi");
                return;
            }

            //
            String[] maNCC = cbx_NhaCC_TSP.getSelectedItem().toString().split("-");
            NhaCungCapDao daoNCC = new NhaCungCapDao();
            NhaCungCap NCC = new NhaCungCap();
            NCC = daoNCC.findMaNhaCCByTen(maNCC[0]);
            if (NCC != null) {
                sp.setNhaCungCap(NCC);
            } else {
                cbx_NhaCC_TSP.setBackground(Color.red);
                MessageDialogHelper.showErrorDialog(null, " Nhà cung cấp không tồn tại, vui lòng nhập lại", "LỖi");
                return;
            }

            //
            String[] maTG = cbx_TacGia_TSP.getSelectedItem().toString().split("-");
            TacGiaDao daoTG = new TacGiaDao();
            TacGia TG = new TacGia();
            TG = daoTG.findMaTacGiaByTen(maTG[0]);
            if (TG != null) {
                sp.setTacGia(TG);
            } else {
                cbx_TacGia_TSP.setBackground(Color.red);
                MessageDialogHelper.showErrorDialog(null, " Tác giả không tồn tại, vui lòng nhập lại", "LỖi");
                return;
            }

            //
            sp.setMaSP(txt_MaSP_TSP.getText());
            sp.setTenSP(txt_TenSP_TSP.getText());
            float donGia = Float.parseFloat(txt_DonGia_TSP.getText());
            sp.setDonGia(donGia);
            sp.setSoLuong((int) sn_SoLuong_TSP.getValue());//
            //
            sp.setHinhSP(personalImage);

            SanPhamDao dao = new SanPhamDao();
            if (dao.insert(sp)) {
                resetTable();
                MessageDialogHelper.showMessageDialog(null, "Sản phẩm thêm thành công", "Thông báo");
                resetThongTinThemSPForm();
                personalImage = null;
                ImageIcon icon = new ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/Screenshot 2021-11-17 090047.jpg"));
                lbl_Hinh_TSP.setIcon(icon);
            } else {
                MessageDialogHelper.showConfirmDialog(null, "Sản phẩm không lưu được do lỗi", "Cảnh báo");

            }

        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(null, e.getMessage(),
                     "Lỗi");
        }
    }//GEN-LAST:event_btn_ThemSP_TSPActionPerformed

    private void btn_Huy_TSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Huy_TSPActionPerformed
        ThemSPForm.setVisible(false);
    }//GEN-LAST:event_btn_Huy_TSPActionPerformed

    private void btn_ChonHinh_TSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChonHinh_TSPActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(new FileFilter() {
            @Override
            public boolean accept(File file) {
                if (file.isDirectory()) {
                    return true;
                } else {
                    return file.getName().toLowerCase().endsWith(".jpg");
                }//To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public String getDescription() {
                return "Image File (*.jpg)"; //To change body of generated methods, choose Tools | Templates.
            }
        });
        if (chooser.showOpenDialog(null) == JFileChooser.CANCEL_OPTION) {
            return;
        }
        File file = chooser.getSelectedFile();
        try {
            ImageIcon icon = new ImageIcon(file.getPath());
            Image img = ImageHelper.resize(icon.getImage(), 150, 150);
            ImageIcon resizedIcon = new ImageIcon(img);
            lbl_Hinh_TSP.setIcon(resizedIcon);
            personalImage = ImageHelper.toByteArray(img, "jpg");
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(null, e.getMessage(), "Lỗi");

        }
    }//GEN-LAST:event_btn_ChonHinh_TSPActionPerformed

    private void txt_DonGia_CNSPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_DonGia_CNSPFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DonGia_CNSPFocusLost

    private void btn_ChonHinh_CNSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChonHinh_CNSPActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(new FileFilter() {
            @Override
            public boolean accept(File file) {
                if (file.isDirectory()) {
                    return true;
                } else {
                    return file.getName().toLowerCase().endsWith(".jpg");
                }//To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public String getDescription() {
                return "Image File (*.jpg)"; //To change body of generated methods, choose Tools | Templates.
            }
        });
        if (chooser.showOpenDialog(null) == JFileChooser.CANCEL_OPTION) {
            return;
        }
        File file = chooser.getSelectedFile();
        try {
            ImageIcon icon = new ImageIcon(file.getPath());
            Image img = ImageHelper.resize(icon.getImage(), 140, 150);
            ImageIcon resizedIcon = new ImageIcon(img);
            lbl_Hinh_CNSP.setIcon(resizedIcon);
            personalImage = ImageHelper.toByteArray(img, "jpg");
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(null, e.getMessage(), "Lỗi");

        }
    }//GEN-LAST:event_btn_ChonHinh_CNSPActionPerformed

    private void txt_MaSP_CNSPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_MaSP_CNSPMouseExited
        try {

            String id = txt_MaSP_CNSP.getText();
            SanPhamDao dao = new SanPhamDao();
            SanPham sp = dao.find(id);

            if (sp != null) {
                txt_MaSP_CNSP.setText(sp.getMaSP().replaceAll("\\s", ""));
                txt_TenSP_CNSP.setText(sp.getTenSP());
                String donGia = String.valueOf(sp.getDonGia());
                txt_DonGia_CNSP.setText(donGia.replaceAll("\\s", ""));
                sn_SoLuong_CNSP.setValue(sp.getSoLuong());

                cbx_NhomSP_CNSP.setSelectedItem(sp.getNhomSanPham().getMaNhomSP().replaceAll("\\s", "") + "-" + sp.getNhomSanPham().getTenNhomSP());
                cbx_NhaCC_CNSP.setSelectedItem(sp.getNhaCungCap().getMaNhaCC().replaceAll("\\s", "") + "-" + sp.getNhaCungCap().getTenNhaCC());
                cbx_TacGia_CNSP.setSelectedItem(sp.getTacGia().getMaTacGia().replaceAll("\\s", "") + "-" + sp.getTacGia().getTenTacGia());

                if (sp.getHinhSP() != null) {
                    Image img = ImageHelper.CreateImageFromByteArray(sp.getHinhSP(), "jpg");
                    lbl_Hinh_CNSP.setIcon(new ImageIcon(img));
                    personalImage = sp.getHinhSP();

                } else {
                    personalImage = sp.getHinhSP();
                    ImageIcon icon = new ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/Screenshot 2021-11-17 090047.jpg"));
                    lbl_Hinh_CNSP.setIcon(icon);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getStackTrace(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txt_MaSP_CNSPMouseExited

    private void txt_MaSP_CNSPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_MaSP_CNSPMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MaSP_CNSPMouseEntered

    private void txt_MaSP_CNSPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_MaSP_CNSPFocusLost

    }//GEN-LAST:event_txt_MaSP_CNSPFocusLost

    private void txt_TenSP_CNSPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_TenSP_CNSPFocusLost

    }//GEN-LAST:event_txt_TenSP_CNSPFocusLost

    private void btn_Huy_CNSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Huy_CNSPActionPerformed
        CapNhapSPForm.setVisible(false);
    }//GEN-LAST:event_btn_Huy_CNSPActionPerformed

    private void btn_CapNhap_CNSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CapNhap_CNSPActionPerformed

        //////////////////////////////////////////////////////////////////////////
        StringBuilder sb = new StringBuilder();

        DataValidator.validateEmptyMaSP(txt_MaSP_CNSP, sb);
        DataValidator.validateEmptyTenNV(txt_TenSP_CNSP, sb);
        DataValidator.validateEmptyDonGia(txt_DonGia_CNSP, sb);
        DataValidator.validateEmptySoLuong(sn_SoLuong_CNSP, sb);
        DataValidator.validateEmptyCBXNhomSP(cbx_NhomSP_CNSP, sb);
        DataValidator.validateEmptyCBXNhaCC(cbx_NhaCC_CNSP, sb);
        DataValidator.validateEmptyCBXTacGia(cbx_TacGia_CNSP, sb);

        //DataValidator.validateEmptyChucVu(txt_ChucVu_CN, sb);
        if (sb.length() > 0) {
            MessageDialogHelper.showErrorDialog(null, sb.toString(), "Lỗi");
            return;
        }
        
        try {
            SanPham sp = new SanPham();

            //
            String[] maNSP = cbx_NhomSP_CNSP.getSelectedItem().toString().split("-");
            NhomSanPhamDao daoNSP = new NhomSanPhamDao();
            NhomSanPham NSP = new NhomSanPham();
            NSP = daoNSP.findMaNhomSPByTen(maNSP[0]);
            if (NSP != null) {
                sp.setNhomSanPham(NSP);
            } else {
                cbx_NhomSP_CNSP.setBackground(Color.red);
                MessageDialogHelper.showErrorDialog(null, " Nhóm sản phẩm không tồn tại, vui lòng nhập lại", "LỖi");
                return;
            }

            //
            String[] maNCC = cbx_NhaCC_CNSP.getSelectedItem().toString().split("-");

            NhaCungCapDao daoNCC = new NhaCungCapDao();
            NhaCungCap NCC = new NhaCungCap();
            NCC = daoNCC.findMaNhaCCByTen(maNCC[0]);
            if (NCC != null) {
                sp.setNhaCungCap(NCC);
            } else {
                cbx_NhaCC_CNSP.setBackground(Color.red);
                MessageDialogHelper.showErrorDialog(null, " Nhà cung cấp không tồn tại, vui lòng nhập lại", "LỖi");
                return;
            }
            //
            String[] maTG = cbx_TacGia_CNSP.getSelectedItem().toString().split("-");
            TacGiaDao daoTG = new TacGiaDao();
            TacGia TG = new TacGia();
            TG = daoTG.findMaTacGiaByTen(maTG[0]);
            if (TG != null) {
                sp.setTacGia(TG);
            } else {
                cbx_TacGia_CNSP.setBackground(Color.red);
                MessageDialogHelper.showErrorDialog(null, " Tác giả không tồn tại, vui lòng nhập lại", "LỖi");
                return;
            }
            //
            if (MessageDialogHelper.showConfirmDialog(null, "Bạn có muốn cập sản phẩm không?", "Hỏi") == JOptionPane.YES_OPTION) {
            } else {
                return;
            }
            //
            sp.setMaSP(txt_MaSP_CNSP.getText());
            sp.setTenSP(txt_TenSP_CNSP.getText());
            float donGia = Float.parseFloat(txt_DonGia_CNSP.getText());
            sp.setDonGia(donGia);
            sp.setSoLuong((int) sn_SoLuong_CNSP.getValue());
            //
            sp.setHinhSP(personalImage);
            SanPhamDao dao = new SanPhamDao();
            if (dao.update(sp)) {
                resetTable();
                MessageDialogHelper.showMessageDialog(null, "Cập nhập sản phẩm thành công", "Thông báo");
                restartFormCapNhap();
                personalImage = null;
                ImageIcon icon = new ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/Screenshot 2021-11-17 090047.jpg"));
                lbl_Hinh_CNSP.setIcon(icon);
            } else {
                MessageDialogHelper.showConfirmDialog(null, "Cập nhập sản phẩm không được do lỗi", "Cảnh báo");

            }

        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(null, e.getMessage(),
                     "Lỗi");
        }
    }//GEN-LAST:event_btn_CapNhap_CNSPActionPerformed

    private void cbx_ChonNhom_QLSPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbx_ChonNhom_QLSPFocusGained


    }//GEN-LAST:event_cbx_ChonNhom_QLSPFocusGained

    private void cbx_ChonNhom_QLSPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbx_ChonNhom_QLSPMouseExited

    }//GEN-LAST:event_cbx_ChonNhom_QLSPMouseExited

    private void cbx_ChonNhaCungCap_QLSPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbx_ChonNhaCungCap_QLSPMouseExited

        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_ChonNhaCungCap_QLSPMouseExited

    private void cbx_ChonTacGia_QLSPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbx_ChonTacGia_QLSPMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_ChonTacGia_QLSPMouseExited

    private void cbx_ChonNhom_QLSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbx_ChonNhom_QLSPMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_ChonNhom_QLSPMouseClicked

    private void pn_TTSP_QLSPMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_TTSP_QLSPMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_pn_TTSP_QLSPMouseMoved

    private void cbx_ChonNhom_QLSPMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbx_ChonNhom_QLSPMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_ChonNhom_QLSPMouseMoved

    private void txt_MaSP_QLSPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_MaSP_QLSPMouseExited

    }//GEN-LAST:event_txt_MaSP_QLSPMouseExited

    private void txt_TenSP_QLSPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_TenSP_QLSPFocusGained
        txt_TenSP_QLSP.setBackground(Color.white); // TODO add your handling code here:
    }//GEN-LAST:event_txt_TenSP_QLSPFocusGained

    private void txt_MaSP_QLSPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_MaSP_QLSPFocusGained
        txt_MaSP_QLSP.setBackground(Color.white); // TODO add your handling code here:
    }//GEN-LAST:event_txt_MaSP_QLSPFocusGained

    private void txt_DonGia_QLSPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_DonGia_QLSPFocusGained
        txt_DonGia_QLSP.setBackground(Color.white); // TODO add your handling code here:
    }//GEN-LAST:event_txt_DonGia_QLSPFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog CapNhapSPForm;
    private javax.swing.JDialog ThemSPForm;
    private javax.swing.JButton btn_CapNhapBang_QLSP;
    private javax.swing.JButton btn_CapNhap_CNSP;
    private javax.swing.JButton btn_CapNhap_QLSP;
    private javax.swing.JButton btn_ChonHinh_CNSP;
    private javax.swing.JButton btn_ChonHinh_TSP;
    private javax.swing.JButton btn_Huy_CNSP;
    private javax.swing.JButton btn_Huy_TSP;
    private javax.swing.JButton btn_ThemSP_QLSP;
    private javax.swing.JButton btn_ThemSP_TSP;
    private javax.swing.JButton btn_TimKiem_TK_QLSP;
    private javax.swing.JButton btn_Xoa_QLSP;
    private javax.swing.JComboBox<String> cbx_ChonNhaCungCap_QLSP;
    private javax.swing.JComboBox<String> cbx_ChonNhom_QLSP;
    private javax.swing.JComboBox<String> cbx_ChonTacGia_QLSP;
    private javax.swing.JComboBox<String> cbx_NhaCC_CNSP;
    private javax.swing.JComboBox<String> cbx_NhaCC_TSP;
    private javax.swing.JComboBox<String> cbx_NhomSP_CNSP;
    private javax.swing.JComboBox<String> cbx_NhomSP_TSP;
    private javax.swing.JComboBox<String> cbx_TacGia_CNSP;
    private javax.swing.JComboBox<String> cbx_TacGia_TSP;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_DonGia_CNSP;
    private javax.swing.JLabel lbl_DonGia_QLSP;
    private javax.swing.JLabel lbl_DonGia_TSP;
    private javax.swing.JLabel lbl_HinhSP_CNSP;
    private javax.swing.JLabel lbl_HinhSP_TSP;
    private javax.swing.JLabel lbl_Hinh_CNSP;
    private javax.swing.JLabel lbl_Hinh_TSP;
    private javax.swing.JLabel lbl_MaNV_QLSP;
    private javax.swing.JLabel lbl_MaSP_CNSP;
    private javax.swing.JLabel lbl_MaSP_TSP;
    private javax.swing.JLabel lbl_NhaCC_CNSP;
    private javax.swing.JLabel lbl_NhaCC_QLSP;
    private javax.swing.JLabel lbl_NhaCC_TSP;
    private javax.swing.JLabel lbl_NhomSP_CNSP;
    private javax.swing.JLabel lbl_NhomSP_QLSP;
    private javax.swing.JLabel lbl_NhomSP_TSP;
    private javax.swing.JLabel lbl_SoLuong_CNSP;
    private javax.swing.JLabel lbl_SoLuong_TSP;
    private javax.swing.JLabel lbl_TacGia_CNSP;
    private javax.swing.JLabel lbl_TacGia_QLSP;
    private javax.swing.JLabel lbl_TacGia_TSP;
    private javax.swing.JLabel lbl_TenForm_QLNV;
    private javax.swing.JLabel lbl_TenNV_QLSP;
    private javax.swing.JLabel lbl_TenSP_CNSP;
    private javax.swing.JLabel lbl_TenSP_TSP;
    private javax.swing.JLabel lbl_TieuCN;
    private javax.swing.JLabel lbl_TieuDe_TSP;
    private javax.swing.JLabel lbl_Tieu_CNSP;
    private javax.swing.JLabel lbl_Tieu_TSP;
    private javax.swing.JPanel pn_ChucNang_CNSP;
    private javax.swing.JPanel pn_ChucNang_QLSP;
    private javax.swing.JPanel pn_ChucNang_TSP;
    private javax.swing.JPanel pn_TTSP_QLSP;
    private javax.swing.JPanel pn_TenForm_CNSP;
    private javax.swing.JPanel pn_TieuDe_CNSP;
    private javax.swing.JPanel pn_TieuDe_TSP;
    private javax.swing.JScrollPane scp_DanhSachSP_QLSP;
    private javax.swing.JSpinner sn_SoLuong_CNSP;
    private javax.swing.JSpinner sn_SoLuong_TSP;
    private javax.swing.JTable tbl_DanhSachSP_QLSP;
    private javax.swing.JTextField txt_DonGia_CNSP;
    private javax.swing.JTextField txt_DonGia_QLSP;
    private javax.swing.JTextField txt_DonGia_TSP;
    private javax.swing.JTextField txt_MaSP_CNSP;
    private javax.swing.JTextField txt_MaSP_QLSP;
    private javax.swing.JTextField txt_MaSP_TSP;
    private javax.swing.JTextField txt_TenSP_CNSP;
    private javax.swing.JTextField txt_TenSP_QLSP;
    private javax.swing.JTextField txt_TenSP_TSP;
    // End of variables declaration//GEN-END:variables
}
