/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.quanlynhanvien.ui;

import com.mycompany.quanlynhanvien.Dao.TaiKhoanDao;
import com.mycompany.quanlynhanvien.Helpers.DataValidator;
import com.mycompany.quanlynhanvien.Helpers.MessageDialogHelper;
import com.mycompany.quanlynhanvien.Helpers.SharedData;
import com.mycompany.quanlynhanvien.model.TaiKhoan;
import java.awt.Color;

/**
 *
 * @author User
 */
public class QuenMKForm extends javax.swing.JDialog {

    /**
     * Creates new form QuenMKForm
     */
    public QuenMKForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_Title = new javax.swing.JPanel();
        lbl_Title = new javax.swing.JLabel();
        lbl_DoiMK = new javax.swing.JLabel();
        lbl_MKCu = new javax.swing.JLabel();
        lbl_MKMoi = new javax.swing.JLabel();
        lbl_NhapLaiMK = new javax.swing.JLabel();
        btn_XacNhan = new javax.swing.JButton();
        btn_Huy = new javax.swing.JButton();
        txt_MKCu = new javax.swing.JPasswordField();
        txt_MKMoi = new javax.swing.JPasswordField();
        txt_NhapLaiMK = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pn_Title.setBackground(new java.awt.Color(0, 255, 255));

        lbl_Title.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Title.setText("Trí Tuệ Việt");

        javax.swing.GroupLayout pn_TitleLayout = new javax.swing.GroupLayout(pn_Title);
        pn_Title.setLayout(pn_TitleLayout);
        pn_TitleLayout.setHorizontalGroup(
            pn_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_TitleLayout.setVerticalGroup(
            pn_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Title, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
        );

        lbl_DoiMK.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_DoiMK.setForeground(new java.awt.Color(51, 204, 255));
        lbl_DoiMK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_DoiMK.setText("Đổi mật khẩu");

        lbl_MKCu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_MKCu.setText("Mật khẩu cũ:");

        lbl_MKMoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_MKMoi.setText("Mật khẩu mới:");

        lbl_NhapLaiMK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_NhapLaiMK.setText("Nhập lại mật khẩu mới:");

        btn_XacNhan.setBackground(new java.awt.Color(102, 255, 102));
        btn_XacNhan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_XacNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-key-20.png"))); // NOI18N
        btn_XacNhan.setText("Xác nhận");
        btn_XacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XacNhanActionPerformed(evt);
            }
        });

        btn_Huy.setBackground(new java.awt.Color(102, 255, 102));
        btn_Huy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Huy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-unavailable-20.png"))); // NOI18N
        btn_Huy.setText("Hủy");
        btn_Huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HuyActionPerformed(evt);
            }
        });

        txt_MKCu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_DoiMK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_NhapLaiMK)
                    .addComponent(lbl_MKMoi)
                    .addComponent(lbl_MKCu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_MKCu)
                    .addComponent(txt_MKMoi)
                    .addComponent(txt_NhapLaiMK, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btn_XacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btn_Huy, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pn_Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_DoiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_MKCu)
                    .addComponent(txt_MKCu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_MKMoi)
                    .addComponent(txt_MKMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_NhapLaiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_NhapLaiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Huy, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_XacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_HuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HuyActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btn_HuyActionPerformed

    private void btn_XacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XacNhanActionPerformed
                                                   
        
        
            
        //////////////////////////////////////////////////////////////////////////
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmptyMatKhau1(txt_MKCu, sb,"Mật khẩu cũ không được để trống");
        DataValidator.validateEmptyMatKhau1(txt_MKMoi, sb,"Mật khẩu mới không được để trống");
        DataValidator.validateEmptyMatKhau1(txt_NhapLaiMK, sb,"Nhập lại mật khẩu không được để trống");
        TaiKhoan tkCu = SharedData.taiKhoanDN;
        String mkCu,mkMoi,nhapLai;
        mkCu = new String(txt_MKCu.getPassword());
        mkMoi = new String(txt_MKMoi.getPassword());
        nhapLai = new String(txt_NhapLaiMK.getPassword());
        if(sb.length()>0)
        {
            MessageDialogHelper.showErrorDialog(null, sb.toString(), "Lỗi");
            return;
        }
        if(mkCu.equals(tkCu.getMatKhau().replaceAll("\\s","")))
        {if(mkMoi.equals(nhapLai))
        {
            
        }else{
            MessageDialogHelper.showErrorDialog(null, "Mật khẩu mới và nhập lại mật khẩu không giống nhau", "Lỗi");
            txt_NhapLaiMK.setBackground(Color.red);
            return;}
        
        try {
            TaiKhoan tk = new TaiKhoan();
            tk.setMaTK(tkCu.getMaTK()); 
            tk.setMatKhau(mkMoi);
            
            TaiKhoanDao dao =new TaiKhoanDao();

            if(dao.update(tk))
            {
               
                MessageDialogHelper.showMessageDialog(null, "Đổi mật khẩu thành công", "Thông báo");
                restartFormQuenMK();
                this.dispose();
            }
            else{
                MessageDialogHelper.showConfirmDialog(null, "Đổi mật khẩu không thành công do lỗi", "Cảnh báo");
            }

        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog( null, e.getMessage()
                , "Lỗi");
        }}
        //else {
       // MessageDialogHelper.showConfirmDialog(null, "Mật khẩu cũ không đúng", "Cảnh báo");txt_MKCu.setBackground(Color.red); }
   
    }//GEN-LAST:event_btn_XacNhanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuenMKForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuenMKForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuenMKForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuenMKForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuenMKForm dialog = new QuenMKForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Huy;
    private javax.swing.JButton btn_XacNhan;
    private javax.swing.JLabel lbl_DoiMK;
    private javax.swing.JLabel lbl_MKCu;
    private javax.swing.JLabel lbl_MKMoi;
    private javax.swing.JLabel lbl_NhapLaiMK;
    private javax.swing.JLabel lbl_Title;
    private javax.swing.JPanel pn_Title;
    private javax.swing.JPasswordField txt_MKCu;
    private javax.swing.JPasswordField txt_MKMoi;
    private javax.swing.JPasswordField txt_NhapLaiMK;
    // End of variables declaration//GEN-END:variables

    private void restartFormQuenMK() {
       txt_MKCu.setText("");
       txt_MKCu.setBackground(Color.white);
       txt_MKMoi.setText("");
       txt_MKMoi.setBackground(Color.white);
       txt_NhapLaiMK.setText("");
       txt_NhapLaiMK.setBackground(Color.white);
    }
}
