/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quanlynhanvien.ui;

/**
 *
 * @author User
 */
public class MayTinhForm extends javax.swing.JFrame {
    
    String operand1 = "";
    String operator = "";
    boolean isEqualsPress = false ; 
    /**
     * Creates new form MayTinhForm
     */
    public MayTinhForm() {
        initComponents();
        setLocation(1100, 450);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Tieu = new javax.swing.JLabel();
        pn_ManHinh = new javax.swing.JPanel();
        txt_ManHinh = new javax.swing.JTextField();
        pn_BanPhim = new javax.swing.JPanel();
        btn_NumBer1 = new javax.swing.JButton();
        btn_NumBer2 = new javax.swing.JButton();
        btn_NumBer3 = new javax.swing.JButton();
        btn_Divide = new javax.swing.JButton();
        btn_SquareRoot = new javax.swing.JButton();
        btn_NumBer4 = new javax.swing.JButton();
        btn_NumBer5 = new javax.swing.JButton();
        btn_NumBer6 = new javax.swing.JButton();
        btn_Multiply = new javax.swing.JButton();
        btn_Percentage = new javax.swing.JButton();
        btn_NumBer7 = new javax.swing.JButton();
        btn_NumBer8 = new javax.swing.JButton();
        btn_NumBer9 = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_Fraction = new javax.swing.JButton();
        btn_NumBer0 = new javax.swing.JButton();
        btn_Plus = new javax.swing.JButton();
        btn_Clear = new javax.swing.JButton();
        btn_Subtract = new javax.swing.JButton();
        btn_Equals = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_Tieu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_Tieu.setText("CASIO");

        pn_ManHinh.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txt_ManHinh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_ManHinh.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout pn_ManHinhLayout = new javax.swing.GroupLayout(pn_ManHinh);
        pn_ManHinh.setLayout(pn_ManHinhLayout);
        pn_ManHinhLayout.setHorizontalGroup(
            pn_ManHinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_ManHinhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_ManHinh)
                .addContainerGap())
        );
        pn_ManHinhLayout.setVerticalGroup(
            pn_ManHinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_ManHinhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_ManHinh, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        pn_BanPhim.setLayout(new java.awt.GridLayout(4, 5, 5, 5));

        btn_NumBer1.setBackground(new java.awt.Color(102, 255, 102));
        btn_NumBer1.setText("1");
        btn_NumBer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NumBer1ActionPerformed(evt);
            }
        });
        pn_BanPhim.add(btn_NumBer1);

        btn_NumBer2.setBackground(new java.awt.Color(102, 255, 102));
        btn_NumBer2.setText("2");
        btn_NumBer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NumBer1ActionPerformed(evt);
            }
        });
        pn_BanPhim.add(btn_NumBer2);

        btn_NumBer3.setBackground(new java.awt.Color(102, 255, 102));
        btn_NumBer3.setText("3");
        btn_NumBer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NumBer1ActionPerformed(evt);
            }
        });
        pn_BanPhim.add(btn_NumBer3);

        btn_Divide.setBackground(new java.awt.Color(102, 255, 102));
        btn_Divide.setText("/");
        btn_Divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        pn_BanPhim.add(btn_Divide);

        btn_SquareRoot.setBackground(new java.awt.Color(102, 255, 102));
        btn_SquareRoot.setText("sqrt");
        btn_SquareRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PercentageActionPerformed(evt);
            }
        });
        pn_BanPhim.add(btn_SquareRoot);

        btn_NumBer4.setBackground(new java.awt.Color(102, 255, 102));
        btn_NumBer4.setText("4");
        btn_NumBer4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NumBer1ActionPerformed(evt);
            }
        });
        pn_BanPhim.add(btn_NumBer4);

        btn_NumBer5.setBackground(new java.awt.Color(102, 255, 102));
        btn_NumBer5.setText("5");
        btn_NumBer5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NumBer1ActionPerformed(evt);
            }
        });
        pn_BanPhim.add(btn_NumBer5);

        btn_NumBer6.setBackground(new java.awt.Color(102, 255, 102));
        btn_NumBer6.setText("6");
        btn_NumBer6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NumBer1ActionPerformed(evt);
            }
        });
        pn_BanPhim.add(btn_NumBer6);

        btn_Multiply.setBackground(new java.awt.Color(102, 255, 102));
        btn_Multiply.setText("*");
        btn_Multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        pn_BanPhim.add(btn_Multiply);

        btn_Percentage.setBackground(new java.awt.Color(102, 255, 102));
        btn_Percentage.setText("%");
        btn_Percentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PercentageActionPerformed(evt);
            }
        });
        pn_BanPhim.add(btn_Percentage);

        btn_NumBer7.setBackground(new java.awt.Color(102, 255, 102));
        btn_NumBer7.setText("7");
        btn_NumBer7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NumBer1ActionPerformed(evt);
            }
        });
        pn_BanPhim.add(btn_NumBer7);

        btn_NumBer8.setBackground(new java.awt.Color(102, 255, 102));
        btn_NumBer8.setText("8");
        btn_NumBer8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NumBer1ActionPerformed(evt);
            }
        });
        pn_BanPhim.add(btn_NumBer8);

        btn_NumBer9.setBackground(new java.awt.Color(102, 255, 102));
        btn_NumBer9.setText("9");
        btn_NumBer9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NumBer1ActionPerformed(evt);
            }
        });
        pn_BanPhim.add(btn_NumBer9);

        btn_add.setBackground(new java.awt.Color(102, 255, 102));
        btn_add.setText("+");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        pn_BanPhim.add(btn_add);

        btn_Fraction.setBackground(new java.awt.Color(102, 255, 102));
        btn_Fraction.setText("1/x");
        btn_Fraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PercentageActionPerformed(evt);
            }
        });
        pn_BanPhim.add(btn_Fraction);

        btn_NumBer0.setBackground(new java.awt.Color(102, 255, 102));
        btn_NumBer0.setText("0");
        btn_NumBer0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NumBer1ActionPerformed(evt);
            }
        });
        pn_BanPhim.add(btn_NumBer0);

        btn_Plus.setBackground(new java.awt.Color(102, 255, 102));
        btn_Plus.setText("+/-");
        btn_Plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PlusActionPerformed(evt);
            }
        });
        pn_BanPhim.add(btn_Plus);

        btn_Clear.setBackground(new java.awt.Color(102, 255, 102));
        btn_Clear.setText("C");
        btn_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClearActionPerformed(evt);
            }
        });
        pn_BanPhim.add(btn_Clear);

        btn_Subtract.setBackground(new java.awt.Color(102, 255, 102));
        btn_Subtract.setText("-");
        btn_Subtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        pn_BanPhim.add(btn_Subtract);

        btn_Equals.setBackground(new java.awt.Color(102, 255, 102));
        btn_Equals.setText("=");
        btn_Equals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EqualsActionPerformed(evt);
            }
        });
        pn_BanPhim.add(btn_Equals);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_BanPhim, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                    .addComponent(pn_ManHinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbl_Tieu)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Tieu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_ManHinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_BanPhim, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_NumBer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NumBer1ActionPerformed
        if(isEqualsPress)
        {
            isEqualsPress = false;
            txt_ManHinh.setText("");
        }
        String cmd = evt.getActionCommand();
        txt_ManHinh.setText(txt_ManHinh.getText() + cmd);
    }//GEN-LAST:event_btn_NumBer1ActionPerformed

    private void btn_PlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PlusActionPerformed
        if(txt_ManHinh.equals("")){return;}
        try {
            double value = Double.parseDouble(txt_ManHinh.getText());
            value = -value;
            txt_ManHinh.setText(""+value);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_PlusActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        String cmd = evt.getActionCommand();
        operator = cmd;
        operand1 = txt_ManHinh.getText();
        txt_ManHinh.setText("");
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_EqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EqualsActionPerformed
        if(txt_ManHinh.getText().equals("")||operand1.equals(""))
        {
                return;
        }
        try {
            double oprand1 = Double.parseDouble(operand1);
            double oprand2 = Double.parseDouble(txt_ManHinh.getText());
            double result = 0;
            if(operator.equals("+"))
            {
                result = oprand1 + oprand2;
            }else if(operator.equals("-"))
            {
                result = oprand1 - oprand2;
            }else if(operator.equals("*"))
            {
                result = oprand1 * oprand2;
            }else if(operator.equals("/"))
            {
                result = oprand1 / oprand2;
            }
            txt_ManHinh.setText(""+result);
            isEqualsPress = true;
        } catch (Exception e) {
            e.printStackTrace();
        }
       
    }//GEN-LAST:event_btn_EqualsActionPerformed

    private void btn_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClearActionPerformed
        txt_ManHinh.setText("");
        operand1 = "";
        operator = "";
        isEqualsPress = false;
    }//GEN-LAST:event_btn_ClearActionPerformed

    private void btn_PercentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PercentageActionPerformed
        if(txt_ManHinh.getText().equals(""))
        {return;}
        String cmd = evt.getActionCommand();
        try {
            double value = Double.parseDouble(txt_ManHinh.getText());
            if(cmd.equals("sqrt"))
            {
                value = Math.sqrt(value);
            }else if(cmd.equals("%"))
            {
                value = value * 100;
            }
            if(cmd.equals("1/x"))
            {
                value = 1/value ;
            }
            txt_ManHinh.setText(""+value);
            isEqualsPress = true;
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_PercentageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MayTinhForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MayTinhForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MayTinhForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MayTinhForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MayTinhForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Clear;
    private javax.swing.JButton btn_Divide;
    private javax.swing.JButton btn_Equals;
    private javax.swing.JButton btn_Fraction;
    private javax.swing.JButton btn_Multiply;
    private javax.swing.JButton btn_NumBer0;
    private javax.swing.JButton btn_NumBer1;
    private javax.swing.JButton btn_NumBer2;
    private javax.swing.JButton btn_NumBer3;
    private javax.swing.JButton btn_NumBer4;
    private javax.swing.JButton btn_NumBer5;
    private javax.swing.JButton btn_NumBer6;
    private javax.swing.JButton btn_NumBer7;
    private javax.swing.JButton btn_NumBer8;
    private javax.swing.JButton btn_NumBer9;
    private javax.swing.JButton btn_Percentage;
    private javax.swing.JButton btn_Plus;
    private javax.swing.JButton btn_SquareRoot;
    private javax.swing.JButton btn_Subtract;
    private javax.swing.JButton btn_add;
    private javax.swing.JLabel lbl_Tieu;
    private javax.swing.JPanel pn_BanPhim;
    private javax.swing.JPanel pn_ManHinh;
    private javax.swing.JTextField txt_ManHinh;
    // End of variables declaration//GEN-END:variables
}
