/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quanlynhanvien.ui;

import com.mycompany.quanlynhanvien.Dao.NhanVienDao;
import com.mycompany.quanlynhanvien.Helpers.ConnectDB;
import com.mycompany.quanlynhanvien.Helpers.DataValidator;
import com.mycompany.quanlynhanvien.Helpers.MessageDialogHelper;
import com.mycompany.quanlynhanvien.model.NhanVien;
import com.mycompany.quanlynhanvien.model.TaiKhoan;
import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.awt.Component;
import java.awt.HeadlessException;
import java.awt.TextField;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.time.LocalDate;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class QLNVForm extends javax.swing.JFrame {

    private DefaultTableModel tblModel;
    /**
     * Creates new form QLNVForm
     */
    public QLNVForm() {
        
        initComponents();
        rb_Nam_QLNV.setSelected(true);
        initTable();
        loadDataToTable();
        setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    private void initTable()
    {
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String [] {"Mã Nhân Viên","Tên Nhân Viên","Giới Tính","Ngày Sinh","Số Điện Thoại","Chức Vụ","Tình Trạng","MaTK"});
        tbl_DanhSachNV_QLNV.setModel(tblModel);
        
    }
    private void loadDataToTable()
    {
        try {
            NhanVienDao dao = new NhanVienDao();
            List<NhanVien> list = dao.findAll();
            tblModel.setRowCount(0);
            for(NhanVien it : list)
            {
                //MessageDialogHelper.showMessageDialog(null, it.getTinhTrang(), "Thông báo");
                tblModel.addRow(new Object[]
                { it.getMaNhanVien(),it.getTenNhanVien(),it.getGioiTinh(),it.getNgaySinh(),it.getsDT(),it.getChucVu(),it.getTinhTrang(),it.getMaTK()} );
                
                tblModel.fireTableDataChanged();
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(null, e.getMessage(), "Lỗi");
                 
        }
    }
    private void restartTable()
    {
        tbl_DanhSachNV_QLNV.clearSelection();
        loadDataToTable();
    }
    public void loadcbxmaTK()
    {
        try {
            NhanVienDao dao = new NhanVienDao();
            List<String> list = dao.findMaTK();
            cbx_MaTK_T.removeAllItems();
            cbx_MaTK_T.addItem("");
            for(String it : list)
            {
                cbx_MaTK_T.addItem(it);
                
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(null, e.getMessage(), "Lỗi");
                 
        }
    }
    public String tuDongLayMa() {
		String maNV = "";
		try {
			Connection con = ConnectDB.getInstance().getConnection();
			String sql = " DECLARE @ID VARCHAR(5)\r\n"
					+ " IF (SELECT COUNT(maNhanVien) FROM NhanVien) = 0\r\n"
					+ " SET @ID = '0'\r\n" 
                                        + " ELSE\r\n"
					+ " SELECT @ID = MAX(RIGHT(rtrim(maNhanVien), 3)) FROM NhanVien\r\n"
                                        + " SELECT @ID = CASE\r\n"
                                        + " WHEN @ID >= 0 and @ID < 9 THEN 'NV00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)\r\n"      
                                        + " WHEN @ID >= 9 THEN 'NV0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)\r\n"
                                        + " END\r\n"
                                        + " select @ID" ;       		
                                
			Statement statement = con.createStatement();
			ResultSet rs = statement.executeQuery(sql);
			while (rs.next()) {
				String ID = rs.getString(1);
				maNV = ID;
			}
		} catch (SQLException e) {
			// TODO: handle exception
			e.printStackTrace();
		}
		return maNV;
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ThemNVForm = new javax.swing.JDialog();
        pn_TieuDe_T = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lbl_TieuDe_T = new javax.swing.JLabel();
        pn_ChucNang_T = new javax.swing.JPanel();
        btn_ThemMoi_T = new javax.swing.JButton();
        btn_Huy_T = new javax.swing.JButton();
        lbl_ChucVu_T = new javax.swing.JLabel();
        txt_SDT_T = new javax.swing.JTextField();
        lbl_SDT_T = new javax.swing.JLabel();
        dc_NgaySinh_T = new com.toedter.calendar.JDateChooser();
        lbl_NgaySinh_T = new javax.swing.JLabel();
        rb_Nam_T = new javax.swing.JRadioButton();
        rb_Nu_T = new javax.swing.JRadioButton();
        lbl_GioiTinh_T = new javax.swing.JLabel();
        txt_TenNV_T = new javax.swing.JTextField();
        lbl_TenNV_T = new javax.swing.JLabel();
        txt_MaNV_T = new javax.swing.JTextField();
        lbl_MaNV_T = new javax.swing.JLabel();
        lbl_MaTK_T = new javax.swing.JLabel();
        cbx_ChucVu_T = new javax.swing.JComboBox<>();
        cbx_MaTK_T = new javax.swing.JComboBox<>();
        CapNhapNVForm = new javax.swing.JDialog();
        pn_TieuDeCN = new javax.swing.JPanel();
        lbl_TieuCN = new javax.swing.JLabel();
        lbl = new javax.swing.JLabel();
        pn_ChucNang_CN = new javax.swing.JPanel();
        btn_CapNhap_CN = new javax.swing.JButton();
        btn_Huy_CN = new javax.swing.JButton();
        lbl_ChucVu_CN = new javax.swing.JLabel();
        lbl_TinhTrang_CN = new javax.swing.JLabel();
        rb_VanLamViec_CN = new javax.swing.JRadioButton();
        rb_DaNghiViec_CN = new javax.swing.JRadioButton();
        txt_SDT_CN = new javax.swing.JTextField();
        lbl_SDT_CN = new javax.swing.JLabel();
        lbl_NgaySinh_CN = new javax.swing.JLabel();
        lbl_GioiTinh_CN = new javax.swing.JLabel();
        rb_GioiTinh_Nam_CN = new javax.swing.JRadioButton();
        rb_GioiTinh_Nu_CN = new javax.swing.JRadioButton();
        lbl_TenNV_CN = new javax.swing.JLabel();
        txt_TenNV_CN = new javax.swing.JTextField();
        txt_MaNV_CN = new javax.swing.JTextField();
        lbl_MaNV_CN = new javax.swing.JLabel();
        dc_NgaySinh_CN = new com.toedter.calendar.JDateChooser();
        lbl_MaTK_CN = new javax.swing.JLabel();
        cbx_ChucVu_CN = new javax.swing.JComboBox<>();
        cbx_maTK_CN = new javax.swing.JComboBox<>();
        btng_NamNu_QLNV = new javax.swing.ButtonGroup();
        btng_NamNu_T = new javax.swing.ButtonGroup();
        btng_NamNu_CN = new javax.swing.ButtonGroup();
        btng_TinhTrang_CN = new javax.swing.ButtonGroup();
        pn_TieuDe_QLNV = new javax.swing.JPanel();
        lbl_TieuDe_QLNV = new javax.swing.JLabel();
        pn_Menu_QLNV = new javax.swing.JPanel();
        btn_TrangChu_QLNV = new javax.swing.JButton();
        btn_QLKH_QLNV = new javax.swing.JButton();
        btn_QLNV_QLNV = new javax.swing.JButton();
        btn_QLSP_QLNV = new javax.swing.JButton();
        btn_QLHD_QLNV = new javax.swing.JButton();
        btn_ThongKe_QLNV = new javax.swing.JButton();
        btn_TaiKhoan_QLNV = new javax.swing.JButton();
        pn_TaiKhoan_Menu = new javax.swing.JPanel();
        lbl_Hinh_Menu = new javax.swing.JLabel();
        lbl_TenTaiKhoan_Menu = new javax.swing.JLabel();
        lbl_ChucVu_Menu = new javax.swing.JLabel();
        btn_DoiMK_Menu = new javax.swing.JButton();
        btn_DangXuat_Menu = new javax.swing.JButton();
        pn_TimKiem_Menu = new javax.swing.JPanel();
        txt_TimKiem_Menu = new javax.swing.JTextField();
        lbl_TimKiem_Menu = new javax.swing.JLabel();
        btn_TimKiemMenu = new javax.swing.JButton();
        pn_TenForm_QLNV = new javax.swing.JPanel();
        lbl_TenForm_QLNV = new javax.swing.JLabel();
        pn_CNTimK_QLNV = new javax.swing.JPanel();
        lbl_MaNV_QLNV = new javax.swing.JLabel();
        lbl_TenNV_QLNV = new javax.swing.JLabel();
        lbl_ChucVu_QLNV = new javax.swing.JLabel();
        lbl_GioiTinh_QLNV = new javax.swing.JLabel();
        txt_ChucVu_QLNV = new javax.swing.JTextField();
        txt_MaNV_QLNV = new javax.swing.JTextField();
        txt_TenNV_QLNV = new javax.swing.JTextField();
        rb_Nam_QLNV = new javax.swing.JRadioButton();
        rb_Nu_QLNV = new javax.swing.JRadioButton();
        scp_DanhSachNV_QLNV = new javax.swing.JScrollPane();
        tbl_DanhSachNV_QLNV = new javax.swing.JTable();
        pn_ChucNang_QLNV = new javax.swing.JPanel();
        btn_ThemNV_QLNV = new javax.swing.JButton();
        btn_Xoa_QLNV = new javax.swing.JButton();
        btn_CapNhap_QLNV = new javax.swing.JButton();
        btn_TimKiem_QLNV = new javax.swing.JButton();
        btn_CapNhapBang_QLNV = new javax.swing.JButton();

        ThemNVForm.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        ThemNVForm.setLocation(new java.awt.Point(0, 0));
        ThemNVForm.setMinimumSize(new java.awt.Dimension(400, 550));
        ThemNVForm.setModal(true);
        ThemNVForm.setName("ThemNVForm"); // NOI18N

        pn_TieuDe_T.setBackground(new java.awt.Color(51, 255, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Trí Tuệ Việt");

        javax.swing.GroupLayout pn_TieuDe_TLayout = new javax.swing.GroupLayout(pn_TieuDe_T);
        pn_TieuDe_T.setLayout(pn_TieuDe_TLayout);
        pn_TieuDe_TLayout.setHorizontalGroup(
            pn_TieuDe_TLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_TieuDe_TLayout.setVerticalGroup(
            pn_TieuDe_TLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        lbl_TieuDe_T.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_TieuDe_T.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_TieuDe_T.setText("Nhập thông tin nhân viên");

        btn_ThemMoi_T.setBackground(new java.awt.Color(51, 255, 51));
        btn_ThemMoi_T.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_ThemMoi_T.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-identification-documents-24.png"))); // NOI18N
        btn_ThemMoi_T.setText("Thêm mới");
        btn_ThemMoi_T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemMoi_TActionPerformed(evt);
            }
        });

        btn_Huy_T.setBackground(new java.awt.Color(51, 255, 51));
        btn_Huy_T.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Huy_T.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-unavailable-24.png"))); // NOI18N
        btn_Huy_T.setText("Hủy");
        btn_Huy_T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Huy_TActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_ChucNang_TLayout = new javax.swing.GroupLayout(pn_ChucNang_T);
        pn_ChucNang_T.setLayout(pn_ChucNang_TLayout);
        pn_ChucNang_TLayout.setHorizontalGroup(
            pn_ChucNang_TLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_ChucNang_TLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btn_ThemMoi_T)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(btn_Huy_T, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        pn_ChucNang_TLayout.setVerticalGroup(
            pn_ChucNang_TLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_ChucNang_TLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pn_ChucNang_TLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ThemMoi_T)
                    .addComponent(btn_Huy_T))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        lbl_ChucVu_T.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_ChucVu_T.setText("Chức vụ:");

        txt_SDT_T.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_SDT_T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SDT_TActionPerformed(evt);
            }
        });

        lbl_SDT_T.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_SDT_T.setText("Số điện thoại:");

        dc_NgaySinh_T.setDateFormatString("MM-dd-yyyy");

        lbl_NgaySinh_T.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_NgaySinh_T.setText("Ngày sinh:");

        btng_NamNu_T.add(rb_Nam_T);
        rb_Nam_T.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rb_Nam_T.setText("Nam");

        btng_NamNu_T.add(rb_Nu_T);
        rb_Nu_T.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rb_Nu_T.setText("Nữ");

        lbl_GioiTinh_T.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_GioiTinh_T.setText("Giới tính:");

        txt_TenNV_T.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbl_TenNV_T.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_TenNV_T.setText("Tên nhân viên:");

        txt_MaNV_T.setEditable(false);
        txt_MaNV_T.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbl_MaNV_T.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_MaNV_T.setText("Mã nhân viên:");

        lbl_MaTK_T.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_MaTK_T.setText("Mã tài khoản:");

        cbx_ChucVu_T.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân viên bán hàng", "Quản lý" }));

        cbx_MaTK_T.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout ThemNVFormLayout = new javax.swing.GroupLayout(ThemNVForm.getContentPane());
        ThemNVForm.getContentPane().setLayout(ThemNVFormLayout);
        ThemNVFormLayout.setHorizontalGroup(
            ThemNVFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_TieuDe_T, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_TieuDe_T, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_ChucNang_T, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ThemNVFormLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(ThemNVFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ThemNVFormLayout.createSequentialGroup()
                        .addGroup(ThemNVFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_SDT_T)
                            .addComponent(lbl_ChucVu_T, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_MaTK_T, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(ThemNVFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_SDT_T)
                            .addComponent(cbx_ChucVu_T, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbx_MaTK_T, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ThemNVFormLayout.createSequentialGroup()
                        .addGroup(ThemNVFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_NgaySinh_T, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_MaNV_T, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_TenNV_T, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_GioiTinh_T, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ThemNVFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dc_NgaySinh_T, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(txt_TenNV_T, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(txt_MaNV_T, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addGroup(ThemNVFormLayout.createSequentialGroup()
                                .addComponent(rb_Nam_T, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_Nu_T)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        ThemNVFormLayout.setVerticalGroup(
            ThemNVFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThemNVFormLayout.createSequentialGroup()
                .addComponent(pn_TieuDe_T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_TieuDe_T, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ThemNVFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_MaNV_T, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_MaNV_T, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ThemNVFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_TenNV_T, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_TenNV_T, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ThemNVFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_Nu_T)
                    .addComponent(rb_Nam_T)
                    .addComponent(lbl_GioiTinh_T, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(ThemNVFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ThemNVFormLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl_NgaySinh_T, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ThemNVFormLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dc_NgaySinh_T, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ThemNVFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_SDT_T, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_SDT_T, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ThemNVFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ChucVu_T, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_ChucVu_T, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ThemNVFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_MaTK_T)
                    .addComponent(cbx_MaTK_T, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(pn_ChucNang_T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        CapNhapNVForm.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        CapNhapNVForm.setLocation(new java.awt.Point(0, 0));
        CapNhapNVForm.setMinimumSize(new java.awt.Dimension(400, 570));
        CapNhapNVForm.setModal(true);

        pn_TieuDeCN.setBackground(new java.awt.Color(0, 255, 255));
        pn_TieuDeCN.setForeground(new java.awt.Color(0, 255, 255));

        lbl_TieuCN.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_TieuCN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_TieuCN.setText("Trí Tuệ Việt");

        javax.swing.GroupLayout pn_TieuDeCNLayout = new javax.swing.GroupLayout(pn_TieuDeCN);
        pn_TieuDeCN.setLayout(pn_TieuDeCNLayout);
        pn_TieuDeCNLayout.setHorizontalGroup(
            pn_TieuDeCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_TieuCN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_TieuDeCNLayout.setVerticalGroup(
            pn_TieuDeCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_TieuCN, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl.setText("Nhập thông tin nhân viên");

        btn_CapNhap_CN.setBackground(new java.awt.Color(51, 255, 51));
        btn_CapNhap_CN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_CapNhap_CN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-identification-documents-24.png"))); // NOI18N
        btn_CapNhap_CN.setText("Cập nhập");
        btn_CapNhap_CN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CapNhap_CNActionPerformed(evt);
            }
        });

        btn_Huy_CN.setBackground(new java.awt.Color(51, 255, 51));
        btn_Huy_CN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Huy_CN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-unavailable-24.png"))); // NOI18N
        btn_Huy_CN.setText("Hủy");
        btn_Huy_CN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Huy_CNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_ChucNang_CNLayout = new javax.swing.GroupLayout(pn_ChucNang_CN);
        pn_ChucNang_CN.setLayout(pn_ChucNang_CNLayout);
        pn_ChucNang_CNLayout.setHorizontalGroup(
            pn_ChucNang_CNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_ChucNang_CNLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btn_CapNhap_CN, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Huy_CN, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        pn_ChucNang_CNLayout.setVerticalGroup(
            pn_ChucNang_CNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_ChucNang_CNLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(pn_ChucNang_CNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_CapNhap_CN)
                    .addComponent(btn_Huy_CN))
                .addGap(20, 20, 20))
        );

        lbl_ChucVu_CN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_ChucVu_CN.setText("Chức vụ:");

        lbl_TinhTrang_CN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_TinhTrang_CN.setText("Tình trạng:");

        btng_TinhTrang_CN.add(rb_VanLamViec_CN);
        rb_VanLamViec_CN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rb_VanLamViec_CN.setText("Vẫn làm việc");

        btng_TinhTrang_CN.add(rb_DaNghiViec_CN);
        rb_DaNghiViec_CN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rb_DaNghiViec_CN.setText("Đã nghỉ việc");

        txt_SDT_CN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_SDT_CN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SDT_CNActionPerformed(evt);
            }
        });

        lbl_SDT_CN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_SDT_CN.setText("Số điện thoại");

        lbl_NgaySinh_CN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_NgaySinh_CN.setText("Ngày sinh:");

        lbl_GioiTinh_CN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_GioiTinh_CN.setText("Giới tính:");

        btng_NamNu_CN.add(rb_GioiTinh_Nam_CN);
        rb_GioiTinh_Nam_CN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rb_GioiTinh_Nam_CN.setText("Nam");

        btng_NamNu_CN.add(rb_GioiTinh_Nu_CN);
        rb_GioiTinh_Nu_CN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rb_GioiTinh_Nu_CN.setText("Nữ ");

        lbl_TenNV_CN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_TenNV_CN.setText("Tên nhân viên:");

        txt_TenNV_CN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_TenNV_CN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_TenNV_CNFocusLost(evt);
            }
        });

        txt_MaNV_CN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_MaNV_CN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_MaNV_CNFocusLost(evt);
            }
        });

        lbl_MaNV_CN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_MaNV_CN.setText("Mã nhân viên:");

        dc_NgaySinh_CN.setDateFormatString("MM-dd-yyyy");
        dc_NgaySinh_CN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dc_NgaySinh_CNFocusLost(evt);
            }
        });

        lbl_MaTK_CN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_MaTK_CN.setText("Mã tài Khoản:");

        cbx_ChucVu_CN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân viên bán hàng", "Quản lý" }));

        cbx_maTK_CN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout CapNhapNVFormLayout = new javax.swing.GroupLayout(CapNhapNVForm.getContentPane());
        CapNhapNVForm.getContentPane().setLayout(CapNhapNVFormLayout);
        CapNhapNVFormLayout.setHorizontalGroup(
            CapNhapNVFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_TieuDeCN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_ChucNang_CN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(CapNhapNVFormLayout.createSequentialGroup()
                .addGroup(CapNhapNVFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CapNhapNVFormLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(CapNhapNVFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_MaNV_CN)
                            .addGroup(CapNhapNVFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lbl_NgaySinh_CN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                .addComponent(lbl_GioiTinh_CN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(CapNhapNVFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lbl_TinhTrang_CN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_SDT_CN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lbl_ChucVu_CN, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_MaTK_CN))
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CapNhapNVFormLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_TenNV_CN)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(CapNhapNVFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_MaNV_CN)
                    .addGroup(CapNhapNVFormLayout.createSequentialGroup()
                        .addComponent(rb_GioiTinh_Nam_CN, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(rb_GioiTinh_Nu_CN, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_SDT_CN)
                    .addComponent(dc_NgaySinh_CN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(CapNhapNVFormLayout.createSequentialGroup()
                        .addComponent(rb_VanLamViec_CN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_DaNghiViec_CN, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_TenNV_CN)
                    .addComponent(cbx_ChucVu_CN, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbx_maTK_CN, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        CapNhapNVFormLayout.setVerticalGroup(
            CapNhapNVFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CapNhapNVFormLayout.createSequentialGroup()
                .addComponent(pn_TieuDeCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CapNhapNVFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_MaNV_CN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_MaNV_CN, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CapNhapNVFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_TenNV_CN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_TenNV_CN, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CapNhapNVFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_GioiTinh_CN, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rb_GioiTinh_Nam_CN)
                    .addComponent(rb_GioiTinh_Nu_CN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CapNhapNVFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dc_NgaySinh_CN, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(lbl_NgaySinh_CN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CapNhapNVFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_SDT_CN, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(lbl_SDT_CN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CapNhapNVFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_TinhTrang_CN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CapNhapNVFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rb_VanLamViec_CN)
                        .addComponent(rb_DaNghiViec_CN)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CapNhapNVFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ChucVu_CN, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(cbx_ChucVu_CN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CapNhapNVFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_MaTK_CN, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_maTK_CN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_ChucNang_CN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);

        pn_TieuDe_QLNV.setBackground(new java.awt.Color(0, 255, 255));

        lbl_TieuDe_QLNV.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbl_TieuDe_QLNV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_TieuDe_QLNV.setText("Trí Tuệ Việt");
        lbl_TieuDe_QLNV.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbl_TieuDe_QLNV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pn_TieuDe_QLNVLayout = new javax.swing.GroupLayout(pn_TieuDe_QLNV);
        pn_TieuDe_QLNV.setLayout(pn_TieuDe_QLNVLayout);
        pn_TieuDe_QLNVLayout.setHorizontalGroup(
            pn_TieuDe_QLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_TieuDe_QLNV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_TieuDe_QLNVLayout.setVerticalGroup(
            pn_TieuDe_QLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_TieuDe_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btn_TrangChu_QLNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_TrangChu_QLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-home-page-40.png"))); // NOI18N
        btn_TrangChu_QLNV.setText("         Trang chủ");
        btn_TrangChu_QLNV.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btn_TrangChu_QLNV.setMinimumSize(new java.awt.Dimension(97, 90));
        btn_TrangChu_QLNV.setPreferredSize(new java.awt.Dimension(97, 90));
        btn_TrangChu_QLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TrangChu_QLNVActionPerformed(evt);
            }
        });

        btn_QLKH_QLNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_QLKH_QLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-user-40.png"))); // NOI18N
        btn_QLKH_QLNV.setText("    Quản lý khách hàng");
        btn_QLKH_QLNV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_QLKH_QLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLKH_QLNVActionPerformed(evt);
            }
        });

        btn_QLNV_QLNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_QLNV_QLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-manager-40.png"))); // NOI18N
        btn_QLNV_QLNV.setText("     Quản lý nhân viên");
        btn_QLNV_QLNV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_QLNV_QLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLNV_QLNVActionPerformed(evt);
            }
        });

        btn_QLSP_QLNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_QLSP_QLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-book-40.png"))); // NOI18N
        btn_QLSP_QLNV.setText("     Quản lý sản phẩm");
        btn_QLSP_QLNV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_QLSP_QLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLSP_QLNVActionPerformed(evt);
            }
        });

        btn_QLHD_QLNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_QLHD_QLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-file-invoice-dollar-40.png"))); // NOI18N
        btn_QLHD_QLNV.setText("     Quản lý hóa đơn");
        btn_QLHD_QLNV.setActionCommand(" Quản lý hóa đơn");
        btn_QLHD_QLNV.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_QLHD_QLNV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_QLHD_QLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLHD_QLNVActionPerformed(evt);
            }
        });

        btn_ThongKe_QLNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_ThongKe_QLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-analytics-40.png"))); // NOI18N
        btn_ThongKe_QLNV.setText("         Thống kê");
        btn_ThongKe_QLNV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_ThongKe_QLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThongKe_QLNVActionPerformed(evt);
            }
        });

        btn_TaiKhoan_QLNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_TaiKhoan_QLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-user-40_1.png"))); // NOI18N
        btn_TaiKhoan_QLNV.setText("         Tài khoản");
        btn_TaiKhoan_QLNV.setHideActionText(true);
        btn_TaiKhoan_QLNV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_TaiKhoan_QLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TaiKhoan_QLNVActionPerformed(evt);
            }
        });

        pn_TaiKhoan_Menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_Hinh_Menu.setText("Hình ");

        lbl_ChucVu_Menu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btn_DoiMK_Menu.setBackground(new java.awt.Color(102, 255, 102));
        btn_DoiMK_Menu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_DoiMK_Menu.setText("Đổi mật khẩu");
        btn_DoiMK_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DoiMK_MenuActionPerformed(evt);
            }
        });

        btn_DangXuat_Menu.setBackground(new java.awt.Color(102, 255, 102));
        btn_DangXuat_Menu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_DangXuat_Menu.setText("Đăng xuất");
        btn_DangXuat_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DangXuat_MenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_TaiKhoan_MenuLayout = new javax.swing.GroupLayout(pn_TaiKhoan_Menu);
        pn_TaiKhoan_Menu.setLayout(pn_TaiKhoan_MenuLayout);
        pn_TaiKhoan_MenuLayout.setHorizontalGroup(
            pn_TaiKhoan_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_TaiKhoan_MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Hinh_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_TaiKhoan_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_TenTaiKhoan_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_ChucVu_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_TaiKhoan_MenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_DoiMK_Menu)
                .addGap(34, 34, 34)
                .addComponent(btn_DangXuat_Menu)
                .addContainerGap())
        );
        pn_TaiKhoan_MenuLayout.setVerticalGroup(
            pn_TaiKhoan_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_TaiKhoan_MenuLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pn_TaiKhoan_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_Hinh_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pn_TaiKhoan_MenuLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbl_TenTaiKhoan_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_ChucVu_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_TaiKhoan_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_DoiMK_Menu)
                    .addComponent(btn_DangXuat_Menu))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pn_TimKiem_Menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt_TimKiem_Menu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbl_TimKiem_Menu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_TimKiem_Menu.setText("Tìm kiếm sản phẩm theo tên sản phẩm");

        btn_TimKiemMenu.setBackground(new java.awt.Color(102, 255, 102));
        btn_TimKiemMenu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_TimKiemMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-search-24.png"))); // NOI18N
        btn_TimKiemMenu.setText("Tìm kiếm");
        btn_TimKiemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_TimKiem_MenuLayout = new javax.swing.GroupLayout(pn_TimKiem_Menu);
        pn_TimKiem_Menu.setLayout(pn_TimKiem_MenuLayout);
        pn_TimKiem_MenuLayout.setHorizontalGroup(
            pn_TimKiem_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_TimKiem_MenuLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btn_TimKiemMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pn_TimKiem_MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_TimKiem_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_TimKiem_Menu)
                    .addComponent(lbl_TimKiem_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                .addContainerGap())
        );
        pn_TimKiem_MenuLayout.setVerticalGroup(
            pn_TimKiem_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_TimKiem_MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_TimKiem_Menu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_TimKiem_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_TimKiemMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pn_Menu_QLNVLayout = new javax.swing.GroupLayout(pn_Menu_QLNV);
        pn_Menu_QLNV.setLayout(pn_Menu_QLNVLayout);
        pn_Menu_QLNVLayout.setHorizontalGroup(
            pn_Menu_QLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_TrangChu_QLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_QLNV_QLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_QLSP_QLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_QLHD_QLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_ThongKe_QLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_TaiKhoan_QLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_QLKH_QLNV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_TaiKhoan_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_TimKiem_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_Menu_QLNVLayout.setVerticalGroup(
            pn_Menu_QLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_Menu_QLNVLayout.createSequentialGroup()
                .addComponent(btn_TrangChu_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_QLKH_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_QLNV_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_QLSP_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_QLHD_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ThongKe_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_TaiKhoan_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(pn_TimKiem_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pn_TaiKhoan_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        btn_TrangChu_QLNV.getAccessibleContext().setAccessibleName("Trang chủ");

        lbl_TenForm_QLNV.setBackground(new java.awt.Color(255, 255, 255));
        lbl_TenForm_QLNV.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_TenForm_QLNV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_TenForm_QLNV.setText("Quản Lý Nhân Viên");
        lbl_TenForm_QLNV.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout pn_TenForm_QLNVLayout = new javax.swing.GroupLayout(pn_TenForm_QLNV);
        pn_TenForm_QLNV.setLayout(pn_TenForm_QLNVLayout);
        pn_TenForm_QLNVLayout.setHorizontalGroup(
            pn_TenForm_QLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_TenForm_QLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_TenForm_QLNVLayout.setVerticalGroup(
            pn_TenForm_QLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_TenForm_QLNVLayout.createSequentialGroup()
                .addComponent(lbl_TenForm_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pn_CNTimK_QLNV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_MaNV_QLNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_MaNV_QLNV.setText("Mã Nhân Viên:");

        lbl_TenNV_QLNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_TenNV_QLNV.setText("Tên Nhân Viên:");

        lbl_ChucVu_QLNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_ChucVu_QLNV.setText("Chức Vụ:");

        lbl_GioiTinh_QLNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_GioiTinh_QLNV.setText("Giới Tính:");

        txt_ChucVu_QLNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_ChucVu_QLNV.setMinimumSize(new java.awt.Dimension(7, 25));
        txt_ChucVu_QLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ChucVu_QLNVActionPerformed(evt);
            }
        });

        txt_MaNV_QLNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_MaNV_QLNV.setMinimumSize(new java.awt.Dimension(7, 25));

        txt_TenNV_QLNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btng_NamNu_QLNV.add(rb_Nam_QLNV);
        rb_Nam_QLNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rb_Nam_QLNV.setText("Nam");
        rb_Nam_QLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_Nam_QLNVActionPerformed(evt);
            }
        });

        btng_NamNu_QLNV.add(rb_Nu_QLNV);
        rb_Nu_QLNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rb_Nu_QLNV.setText("Nữ");

        javax.swing.GroupLayout pn_CNTimK_QLNVLayout = new javax.swing.GroupLayout(pn_CNTimK_QLNV);
        pn_CNTimK_QLNV.setLayout(pn_CNTimK_QLNVLayout);
        pn_CNTimK_QLNVLayout.setHorizontalGroup(
            pn_CNTimK_QLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_CNTimK_QLNVLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(pn_CNTimK_QLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pn_CNTimK_QLNVLayout.createSequentialGroup()
                        .addComponent(lbl_MaNV_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(txt_MaNV_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_CNTimK_QLNVLayout.createSequentialGroup()
                        .addComponent(lbl_TenNV_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_TenNV_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(120, 120, 120)
                .addGroup(pn_CNTimK_QLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_ChucVu_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_GioiTinh_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_CNTimK_QLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_CNTimK_QLNVLayout.createSequentialGroup()
                        .addComponent(rb_Nam_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(rb_Nu_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_ChucVu_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_CNTimK_QLNVLayout.setVerticalGroup(
            pn_CNTimK_QLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_CNTimK_QLNVLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pn_CNTimK_QLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_MaNV_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_MaNV_QLNV)
                    .addComponent(txt_ChucVu_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ChucVu_QLNV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(pn_CNTimK_QLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_TenNV_QLNV)
                    .addComponent(txt_TenNV_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_GioiTinh_QLNV)
                    .addComponent(rb_Nam_QLNV)
                    .addComponent(rb_Nu_QLNV))
                .addGap(40, 40, 40))
        );

        tbl_DanhSachNV_QLNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbl_DanhSachNV_QLNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã NV", "Tên Nhân Viên", "Giới tính", "Ngày sinh", "Số điện thoại", "Chức vụ", "Tình trạng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_DanhSachNV_QLNV.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbl_DanhSachNV_QLNV.setName("Danh sách nhân viên\n"); // NOI18N
        tbl_DanhSachNV_QLNV.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tbl_DanhSachNV_QLNVFocusLost(evt);
            }
        });
        scp_DanhSachNV_QLNV.setViewportView(tbl_DanhSachNV_QLNV);

        btn_ThemNV_QLNV.setBackground(new java.awt.Color(51, 255, 51));
        btn_ThemNV_QLNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_ThemNV_QLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-identification-documents-24.png"))); // NOI18N
        btn_ThemNV_QLNV.setText("Thêm mới");
        btn_ThemNV_QLNV.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_ThemNV_QLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemNV_QLNVActionPerformed(evt);
            }
        });

        btn_Xoa_QLNV.setBackground(new java.awt.Color(51, 255, 51));
        btn_Xoa_QLNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Xoa_QLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-user-24.png"))); // NOI18N
        btn_Xoa_QLNV.setText("-  Xóa");
        btn_Xoa_QLNV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Xoa_QLNV.setMinimumSize(new java.awt.Dimension(93, 25));
        btn_Xoa_QLNV.setPreferredSize(new java.awt.Dimension(93, 25));
        btn_Xoa_QLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Xoa_QLNVActionPerformed(evt);
            }
        });

        btn_CapNhap_QLNV.setBackground(new java.awt.Color(102, 255, 102));
        btn_CapNhap_QLNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_CapNhap_QLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-pencil-24.png"))); // NOI18N
        btn_CapNhap_QLNV.setText("Cập nhập");
        btn_CapNhap_QLNV.setFocusable(false);
        btn_CapNhap_QLNV.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_CapNhap_QLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CapNhap_QLNVActionPerformed(evt);
            }
        });

        btn_TimKiem_QLNV.setBackground(new java.awt.Color(51, 255, 51));
        btn_TimKiem_QLNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_TimKiem_QLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-search-24.png"))); // NOI18N
        btn_TimKiem_QLNV.setText("Tìm kiếm");
        btn_TimKiem_QLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiem_QLNVActionPerformed(evt);
            }
        });

        btn_CapNhapBang_QLNV.setBackground(new java.awt.Color(51, 255, 51));
        btn_CapNhapBang_QLNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_CapNhapBang_QLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-easel-24.png"))); // NOI18N
        btn_CapNhapBang_QLNV.setText("Cập nhập lại bảng");
        btn_CapNhapBang_QLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CapNhapBang_QLNVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_ChucNang_QLNVLayout = new javax.swing.GroupLayout(pn_ChucNang_QLNV);
        pn_ChucNang_QLNV.setLayout(pn_ChucNang_QLNVLayout);
        pn_ChucNang_QLNVLayout.setHorizontalGroup(
            pn_ChucNang_QLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_ChucNang_QLNVLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(btn_TimKiem_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(btn_ThemNV_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(btn_Xoa_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(btn_CapNhap_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(btn_CapNhapBang_QLNV)
                .addGap(72, 72, 72))
        );
        pn_ChucNang_QLNVLayout.setVerticalGroup(
            pn_ChucNang_QLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_ChucNang_QLNVLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pn_ChucNang_QLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_CapNhap_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_CapNhapBang_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_TimKiem_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ThemNV_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Xoa_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_TieuDe_QLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pn_Menu_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_TenForm_QLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_CNTimK_QLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_ChucNang_QLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scp_DanhSachNV_QLNV, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pn_TieuDe_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_Menu_QLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pn_TenForm_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pn_CNTimK_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pn_ChucNang_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scp_DanhSachNV_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_TrangChu_QLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TrangChu_QLNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_TrangChu_QLNVActionPerformed

    private void btn_QLKH_QLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLKH_QLNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_QLKH_QLNVActionPerformed

    private void btn_QLSP_QLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLSP_QLNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_QLSP_QLNVActionPerformed

    private void rb_Nam_QLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_Nam_QLNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_Nam_QLNVActionPerformed

    private void txt_ChucVu_QLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ChucVu_QLNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ChucVu_QLNVActionPerformed

    private void btn_ThemNV_QLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemNV_QLNVActionPerformed
       
        resetThongTinThemNVForm();
                      
        ThemNVForm.setLocationRelativeTo(null);
        ThemNVForm.setVisible(true);
        
         
    }//GEN-LAST:event_btn_ThemNV_QLNVActionPerformed

    private void resetThongTinThemNVForm() throws HeadlessException {
        resetTextFiled(txt_TenNV_T);
        resetTextFiled(dc_NgaySinh_T);
        resetTextFiled(txt_SDT_T);
        txt_MaNV_T.setText(tuDongLayMa());
        rb_Nam_T.setSelected(true);
        cbx_ChucVu_T.setSelectedIndex(0);
        loadcbxmaTK();
        //resetTextFiled(txt_ChucVu_T);
    }

    private void btn_CapNhap_QLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CapNhap_QLNVActionPerformed
        CapNhapNVForm.setLocationRelativeTo(null);
        restartFormCapNhap();               
        CapNhapNVForm.setVisible(true);
        
    }//GEN-LAST:event_btn_CapNhap_QLNVActionPerformed

    private void restartFormCapNhap() throws HeadlessException {
        resetTextFiled(txt_MaNV_CN);
        resetTextFiled(txt_TenNV_CN);
        resetTextFiled(dc_NgaySinh_CN);
        resetTextFiled(txt_SDT_CN);
        //resetTextFiled(txt_ChucVu_CN);
        rb_GioiTinh_Nam_CN.setSelected(true);
        rb_VanLamViec_CN.setSelected(true);
        //String id = (String) tbl_DanhSachNV_QLNV.getValueAt(tbl_DanhSachNV_QLNV.getSelectedRow(), 7);
        NhapTTCapNhapTTable();
        loadcbxmaTK_CN();
    }

    private void resetTextFiled(JTextField field) throws HeadlessException {
       field.setText("");
       field.setBackground(Color.white);
    }

    private void btn_Huy_TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Huy_TActionPerformed
        ThemNVForm.setVisible(false);
    }//GEN-LAST:event_btn_Huy_TActionPerformed
    private int kt_NhapTK(JTextField field1,JTextField field2,JTextField field3)
    {
        int i=0;
        if(field1.getText().equals(""))i=i+1;
        if(field2.getText().equals(""))i=i+1;
        if(field3.getText().equals(""))i=i+1;
        return i;
    }
    private void btn_TimKiem_QLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiem_QLNVActionPerformed
        try {
            NhanVienDao dao = new NhanVienDao();
            List<NhanVien> list = dao.findDK(txt_MaNV_QLNV.getText(), txt_TenNV_QLNV.getText(), txt_ChucVu_QLNV.getText(), rb_Nam_QLNV.isSelected()?"Nam":"Nữ");
            tblModel.setRowCount(0);
            for(NhanVien it : list)
            {
                //MessageDialogHelper.showMessageDialog(null, it.getTinhTrang(), "Thông báo");
                tblModel.addRow(new Object[]
                { it.getMaNhanVien(),it.getTenNhanVien(),it.getGioiTinh(),it.getNgaySinh(),it.getsDT(),it.getChucVu(),it.getTinhTrang(),it.getMaTK()} );
                
                tblModel.fireTableDataChanged();
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(null, e.getMessage(), "Lỗi");
                 
        }
            
        
    }//GEN-LAST:event_btn_TimKiem_QLNVActionPerformed
     
    private void btn_ThemMoi_TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemMoi_TActionPerformed
        StringBuilder sb = new StringBuilder();
        //MessageDialogHelper.showMessageDialog(null, (String) cbx_MaTK_T.getSelectedItem(), "Thông báo");
        DataValidator.validateEmptyTenNV(txt_TenNV_T, sb);
        DataValidator.validateEmpty(dc_NgaySinh_T, sb, "Ngày sinh không được để trống và theo định dạng MM-dd-yyyy");
        DataValidator.validateEmptySDT(txt_SDT_T, sb);
        //DataValidator.validateEmptyChucVu(txt_ChucVu_T, sb);
        if(sb.length()>0)
        {
            MessageDialogHelper.showErrorDialog(null, sb.toString(), "Lỗi");
            return;
        }
        
        try {
            NhanVien nv = new NhanVien();
            nv.setMaNhanVien(txt_MaNV_T.getText());
            nv.setTenNhanVien(txt_TenNV_T.getText());
            nv.setGioiTinh(rb_Nam_T.isSelected()?"Nam":"Nữ");
            nv.setNgaySinh(((JTextField)dc_NgaySinh_T.getDateEditor().getUiComponent()).getText());//
            nv.setsDT(txt_SDT_T.getText());
            nv.setChucVu(cbx_ChucVu_T.getSelectedItem().toString());           
            nv.setMaTK(cbx_MaTK_T.getSelectedItem().toString());
            nv.setTinhTrang("Vẫn làm việc");
             
            NhanVienDao dao =new NhanVienDao();
           if(dao.insert(nv))
           {
               resetTable();
               MessageDialogHelper.showMessageDialog(null, "Nhân viên thêm thành công", "Thông báo");
               resetThongTinThemNVForm();
           }
           else{
               MessageDialogHelper.showConfirmDialog(null, "Sinh viên không lưu được do lỗi", "Cảnh báo");
           }
            
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog( null, e.getMessage()
                    , "Lỗi");
        }
    }//GEN-LAST:event_btn_ThemMoi_TActionPerformed

    private void txt_SDT_TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SDT_TActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SDT_TActionPerformed

    private void btn_Xoa_QLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Xoa_QLNVActionPerformed
        //StringBuilder sb = new StringBuilder();
        //Kiểm tra có chọn trong table
        String maNhanVien = "" ;
        try {
            int row = tbl_DanhSachNV_QLNV.getSelectedRow(); 
        
        if(row>=0)
        {
        String id = (String) tblModel.getValueAt(row , 0);
        maNhanVien = JOptionPane.showInputDialog("Nhập mã nhân viên muốn xóa",id);
        }else{
        maNhanVien = JOptionPane.showInputDialog("Nhập mã nhân viên muốn xóa");
        }      
        } catch (Exception e) {
        }
        //Xóa nhân viên
        if(MessageDialogHelper.showConfirmDialog(null, "Bạn có muốn xóa nhân viên không?", "Hỏi")==JOptionPane.NO_OPTION)
        {return;}
       
        //JOptionPane.showMessageDialog(null, maNhanVien==null);
        if((maNhanVien==null)==false)
        {
        if(maNhanVien.equals("")==false)
        {
             try {
            
            NhanVienDao dao =new NhanVienDao();

            if(dao.delete(maNhanVien))
            {
                resetTable();
                MessageDialogHelper.showMessageDialog(null, "Xóa nhân viên thành công", "Thông báo");
                
            }
            else{
                MessageDialogHelper.showConfirmDialog(null, "Xóa nhân viên không được do lỗi", "Cảnh báo");
            }

        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog( null, e.getMessage()
                , "Lỗi");
        }
        }
        }
    }//GEN-LAST:event_btn_Xoa_QLNVActionPerformed

    private void txt_SDT_CNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SDT_CNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SDT_CNActionPerformed

    private void btn_Huy_CNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Huy_CNActionPerformed
        CapNhapNVForm.setVisible(false);
    }//GEN-LAST:event_btn_Huy_CNActionPerformed

    private void btn_CapNhap_CNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CapNhap_CNActionPerformed
        
        
            
        //////////////////////////////////////////////////////////////////////////
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmptyMaNV(txt_MaNV_CN, sb);
        DataValidator.validateEmptyTenNV(txt_TenNV_CN, sb);
        DataValidator.validateEmpty(dc_NgaySinh_CN, sb, "Ngày sinh không được để trống và theo định dạng MM/dd/yyyy");
        DataValidator.validateEmptySDT(txt_SDT_CN, sb);
        //DataValidator.validateEmptyChucVu(txt_ChucVu_CN, sb);
        if(sb.length()>0)
        {
            MessageDialogHelper.showErrorDialog(null, sb.toString(), "Lỗi");
            return;
        }
        if(MessageDialogHelper.showConfirmDialog(null, "Bạn có muốn cập nhân viên không?", "Hỏi")==JOptionPane.NO_OPTION)
        {return;}
        try {
            NhanVien nv =new NhanVien();
            nv.setMaNhanVien(txt_MaNV_CN.getText());
            nv.setTenNhanVien(txt_TenNV_CN.getText());
            nv.setGioiTinh(rb_GioiTinh_Nam_CN.isSelected()?"Nam":"Nữ");           
            nv.setNgaySinh(((JTextField)dc_NgaySinh_CN.getDateEditor().getUiComponent()).getText());
            nv.setsDT(txt_SDT_CN.getText());
            nv.setChucVu((String) cbx_ChucVu_CN.getSelectedItem());
            nv.setTinhTrang(rb_VanLamViec_CN.isSelected()?"Vẫn làm việc":"Đã nghỉ việc");
            
            nv.setMaTK(cbx_maTK_CN.getSelectedItem().toString());
           
            NhanVienDao dao =new NhanVienDao();

            if(dao.update(nv))
            {
                resetTable();
                MessageDialogHelper.showMessageDialog(null, "Cập nhập nhân viên thành công", "Thông báo");
                restartFormCapNhap();
            }
            else{
                MessageDialogHelper.showConfirmDialog(null, "Cập nhập nhân viên không được do lỗi", "Cảnh báo");
            }

        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog( null, e.getMessage()
                , "Lỗi");
        }
    }//GEN-LAST:event_btn_CapNhap_CNActionPerformed

    private void txt_MaNV_CNFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_MaNV_CNFocusLost
       try {
            
            
            String id = txt_MaNV_CN.getText();
            NhanVienDao dao = new NhanVienDao();
            NhanVien nv = dao.find(id);
            
            if(nv!=null)
            {
                txt_MaNV_CN.setText(nv.getMaNhanVien().replaceAll("\\s",""));
                txt_TenNV_CN.setText(nv.getTenNhanVien());
                Date ns0 = new SimpleDateFormat("yyyy-MM-dd").parse(nv.getNgaySinh());
                
                String ns1 = new SimpleDateFormat("MM-dd-yyyy").format(ns0);
                Date ns2 = new SimpleDateFormat("MM-dd-yyyy").parse(ns1);
                dc_NgaySinh_CN.setDate(ns2);
                txt_SDT_CN.setText(nv.getsDT().replaceAll("\\s",""));
                if(nv.getGioiTinh().replaceAll("\\s","").equals("Nam"))
                {rb_GioiTinh_Nam_CN.setSelected(true);}else{rb_GioiTinh_Nu_CN.setSelected(true);}
                //MessageDialogHelper.showConfirmDialog(null, nv.getTinhTrang(), "Cảnh báo");
                if(nv.getTinhTrang().replaceAll("\\s","").equals("Vẫnlàmviệc"))
                {rb_VanLamViec_CN.setSelected(true);}
                else{rb_DaNghiViec_CN.setSelected(true);}                              
                cbx_ChucVu_CN.setSelectedIndex(nv.getChucVu().replaceAll("\\s","").equals("Quảnlý")?1:0);
                cbx_maTK_CN.removeAllItems();
                cbx_maTK_CN.addItem(nv.getMaTK()==null?"":nv.getMaTK());
                loadcbxmaTK_CN();
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getStackTrace(),"Lỗi",JOptionPane.ERROR_MESSAGE);
        }
        
       
    }//GEN-LAST:event_txt_MaNV_CNFocusLost

    private void txt_TenNV_CNFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_TenNV_CNFocusLost
        
    }//GEN-LAST:event_txt_TenNV_CNFocusLost

    private void dc_NgaySinh_CNFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dc_NgaySinh_CNFocusLost
         
       
    }//GEN-LAST:event_dc_NgaySinh_CNFocusLost

    private void tbl_DanhSachNV_QLNVFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbl_DanhSachNV_QLNVFocusLost
        
    }//GEN-LAST:event_tbl_DanhSachNV_QLNVFocusLost

    private void btn_QLNV_QLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLNV_QLNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_QLNV_QLNVActionPerformed

    private void btn_QLHD_QLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLHD_QLNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_QLHD_QLNVActionPerformed

    private void btn_ThongKe_QLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThongKe_QLNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ThongKe_QLNVActionPerformed

    private void btn_TaiKhoan_QLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TaiKhoan_QLNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_TaiKhoan_QLNVActionPerformed

    private void btn_CapNhapBang_QLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CapNhapBang_QLNVActionPerformed
        resetTable();
    }//GEN-LAST:event_btn_CapNhapBang_QLNVActionPerformed

    private void btn_DoiMK_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DoiMK_MenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_DoiMK_MenuActionPerformed

    private void btn_TimKiemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_TimKiemMenuActionPerformed

    private void btn_DangXuat_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DangXuat_MenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_DangXuat_MenuActionPerformed

    private void resetTable() {
        tblModel.setRowCount(0);
        loadDataToTable();
    }

    private void NhapTTCapNhapTTable() throws HeadlessException {
        
            try {
            int row = tbl_DanhSachNV_QLNV.getSelectedRow();
            //MessageDialogHelper.showConfirmDialog(null, ""+row, "Cảnh báo");
            if(row>=0)
            {
            String id = (String) tbl_DanhSachNV_QLNV.getValueAt(row, 0);
            NhanVienDao dao = new NhanVienDao();
            NhanVien nv = dao.find(id);
            
            if(nv!=null)
            {
                txt_MaNV_CN.setText(nv.getMaNhanVien().replaceAll("\\s",""));
                txt_TenNV_CN.setText(nv.getTenNhanVien());
                Date ns0 = new SimpleDateFormat("yyyy-MM-dd").parse(nv.getNgaySinh());
                String ns1 = new SimpleDateFormat("MM-dd-yyyy").format(ns0);
                Date ns2 = new SimpleDateFormat("MM-dd-yyyy").parse(ns1);
                dc_NgaySinh_CN.setDate(ns2);
                if(nv.getGioiTinh().replaceAll("\\s","").equals("Nam"))
                {rb_GioiTinh_Nam_CN.setSelected(true);}else{rb_GioiTinh_Nu_CN.setSelected(true);}
                //MessageDialogHelper.showConfirmDialog(null, nv.getTinhTrang(), "Cảnh báo");
                if(nv.getTinhTrang().replaceAll("\\s","").equals("Vẫnlàmviệc"))
                {rb_VanLamViec_CN.setSelected(true);}
                else{rb_DaNghiViec_CN.setSelected(true);}              
                txt_SDT_CN.setText(nv.getsDT().replaceAll("\\s",""));
                cbx_ChucVu_CN.setSelectedIndex(nv.getChucVu().replaceAll("\\s","").equals("Quảnlý")?1:0);
                cbx_maTK_CN.removeAllItems();
                cbx_maTK_CN.addItem(nv.getMaTK()==null?"":nv.getMaTK());
            }}else{cbx_maTK_CN.removeAllItems();}
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getStackTrace(),"Lỗi",JOptionPane.ERROR_MESSAGE);
        }
        
    }

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLNVForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLNVForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLNVForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLNVForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLNVForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog CapNhapNVForm;
    private javax.swing.JDialog ThemNVForm;
    private javax.swing.JButton btn_CapNhapBang_QLNV;
    private javax.swing.JButton btn_CapNhap_CN;
    private javax.swing.JButton btn_CapNhap_QLNV;
    private javax.swing.JButton btn_DangXuat_Menu;
    private javax.swing.JButton btn_DoiMK_Menu;
    private javax.swing.JButton btn_Huy_CN;
    private javax.swing.JButton btn_Huy_T;
    private javax.swing.JButton btn_QLHD_QLNV;
    private javax.swing.JButton btn_QLKH_QLNV;
    private javax.swing.JButton btn_QLNV_QLNV;
    private javax.swing.JButton btn_QLSP_QLNV;
    private javax.swing.JButton btn_TaiKhoan_QLNV;
    private javax.swing.JButton btn_ThemMoi_T;
    private javax.swing.JButton btn_ThemNV_QLNV;
    private javax.swing.JButton btn_ThongKe_QLNV;
    private javax.swing.JButton btn_TimKiemMenu;
    private javax.swing.JButton btn_TimKiem_QLNV;
    private javax.swing.JButton btn_TrangChu_QLNV;
    private javax.swing.JButton btn_Xoa_QLNV;
    private javax.swing.ButtonGroup btng_NamNu_CN;
    private javax.swing.ButtonGroup btng_NamNu_QLNV;
    private javax.swing.ButtonGroup btng_NamNu_T;
    private javax.swing.ButtonGroup btng_TinhTrang_CN;
    private javax.swing.JComboBox<String> cbx_ChucVu_CN;
    private javax.swing.JComboBox<String> cbx_ChucVu_T;
    private javax.swing.JComboBox<String> cbx_MaTK_T;
    private javax.swing.JComboBox<String> cbx_maTK_CN;
    private com.toedter.calendar.JDateChooser dc_NgaySinh_CN;
    private com.toedter.calendar.JDateChooser dc_NgaySinh_T;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lbl_ChucVu_CN;
    private javax.swing.JLabel lbl_ChucVu_Menu;
    private javax.swing.JLabel lbl_ChucVu_QLNV;
    private javax.swing.JLabel lbl_ChucVu_T;
    private javax.swing.JLabel lbl_GioiTinh_CN;
    private javax.swing.JLabel lbl_GioiTinh_QLNV;
    private javax.swing.JLabel lbl_GioiTinh_T;
    private javax.swing.JLabel lbl_Hinh_Menu;
    private javax.swing.JLabel lbl_MaNV_CN;
    private javax.swing.JLabel lbl_MaNV_QLNV;
    private javax.swing.JLabel lbl_MaNV_T;
    private javax.swing.JLabel lbl_MaTK_CN;
    private javax.swing.JLabel lbl_MaTK_T;
    private javax.swing.JLabel lbl_NgaySinh_CN;
    private javax.swing.JLabel lbl_NgaySinh_T;
    private javax.swing.JLabel lbl_SDT_CN;
    private javax.swing.JLabel lbl_SDT_T;
    private javax.swing.JLabel lbl_TenForm_QLNV;
    private javax.swing.JLabel lbl_TenNV_CN;
    private javax.swing.JLabel lbl_TenNV_QLNV;
    private javax.swing.JLabel lbl_TenNV_T;
    private javax.swing.JLabel lbl_TenTaiKhoan_Menu;
    private javax.swing.JLabel lbl_TieuCN;
    private javax.swing.JLabel lbl_TieuDe_QLNV;
    private javax.swing.JLabel lbl_TieuDe_T;
    private javax.swing.JLabel lbl_TimKiem_Menu;
    private javax.swing.JLabel lbl_TinhTrang_CN;
    private javax.swing.JPanel pn_CNTimK_QLNV;
    private javax.swing.JPanel pn_ChucNang_CN;
    private javax.swing.JPanel pn_ChucNang_QLNV;
    private javax.swing.JPanel pn_ChucNang_T;
    private javax.swing.JPanel pn_Menu_QLNV;
    private javax.swing.JPanel pn_TaiKhoan_Menu;
    private javax.swing.JPanel pn_TenForm_QLNV;
    private javax.swing.JPanel pn_TieuDeCN;
    private javax.swing.JPanel pn_TieuDe_QLNV;
    private javax.swing.JPanel pn_TieuDe_T;
    private javax.swing.JPanel pn_TimKiem_Menu;
    private javax.swing.JRadioButton rb_DaNghiViec_CN;
    private javax.swing.JRadioButton rb_GioiTinh_Nam_CN;
    private javax.swing.JRadioButton rb_GioiTinh_Nu_CN;
    private javax.swing.JRadioButton rb_Nam_QLNV;
    private javax.swing.JRadioButton rb_Nam_T;
    private javax.swing.JRadioButton rb_Nu_QLNV;
    private javax.swing.JRadioButton rb_Nu_T;
    private javax.swing.JRadioButton rb_VanLamViec_CN;
    private javax.swing.JScrollPane scp_DanhSachNV_QLNV;
    private javax.swing.JTable tbl_DanhSachNV_QLNV;
    private javax.swing.JTextField txt_ChucVu_QLNV;
    private javax.swing.JTextField txt_MaNV_CN;
    private javax.swing.JTextField txt_MaNV_QLNV;
    private javax.swing.JTextField txt_MaNV_T;
    private javax.swing.JTextField txt_SDT_CN;
    private javax.swing.JTextField txt_SDT_T;
    private javax.swing.JTextField txt_TenNV_CN;
    private javax.swing.JTextField txt_TenNV_QLNV;
    private javax.swing.JTextField txt_TenNV_T;
    private javax.swing.JTextField txt_TimKiem_Menu;
    // End of variables declaration//GEN-END:variables

    private void resetTextFiled(JDateChooser field) {
         field.setDate(null);
         field.setBackground(Color.white);//To change body of generated methods, choose Tools | Templates.
    }

    private void loadcbxmaTK_CN() {
         try {
            NhanVienDao dao = new NhanVienDao();
            List<String> list = dao.findMaTK();            
            //cbx_maTK_CN.addItem(maTK);
            cbx_maTK_CN.addItem("");
            for(String it : list)
            {
                cbx_maTK_CN.addItem(it);
                
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(null, e.getMessage(), "Lỗi");
                 
        }
    }
}
