/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quanlynhanvien.ui;

import javax.swing.JFrame;

/**
 *
 * @author User
 */
public class TaiKhoanForm extends javax.swing.JFrame {

    /**
     * Creates new form TaiKhoanForm
     */
    public TaiKhoanForm() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btng_NamNu_TaiKhoan = new javax.swing.ButtonGroup();
        pn_TieuDe_QLNV = new javax.swing.JPanel();
        lbl_TieuDe_QLNV = new javax.swing.JLabel();
        pn_Menu_QLNV = new javax.swing.JPanel();
        btn_TrangChu_QLNV = new javax.swing.JButton();
        btn_QLKH_QLNV = new javax.swing.JButton();
        btn_QLNV_QLNV = new javax.swing.JButton();
        btn_QLSP_QLNV = new javax.swing.JButton();
        btn_QLHD_QLNV = new javax.swing.JButton();
        btn_ThongKe_QLNV = new javax.swing.JButton();
        btn_TaiKhoan_QLNV = new javax.swing.JButton();
        pn_TaiKhoan_Menu = new javax.swing.JPanel();
        lbl_Hinh_Menu = new javax.swing.JLabel();
        lbl_TenTaiKhoan_Menu = new javax.swing.JLabel();
        lbl_ChucVu_Menu = new javax.swing.JLabel();
        btn_DoiMK_Menu = new javax.swing.JButton();
        btn_DangXuat_Menu = new javax.swing.JButton();
        pn_TimKiem_Menu = new javax.swing.JPanel();
        txt_TimKiem_Menu = new javax.swing.JTextField();
        lbl_TimKiem_Menu = new javax.swing.JLabel();
        btn_TimKiemMenu = new javax.swing.JButton();
        pn_TTTaiKhoan = new javax.swing.JPanel();
        lbl_Tieu_TaiKhoan = new javax.swing.JLabel();
        lbl_TTTaiKhoan = new javax.swing.JLabel();
        lbl_MaTK = new javax.swing.JLabel();
        lbl_TenNV = new javax.swing.JLabel();
        lbl_GioiTinh = new javax.swing.JLabel();
        lbl_Ngaysinh = new javax.swing.JLabel();
        lbl_SDT = new javax.swing.JLabel();
        lbl_ChucVu = new javax.swing.JLabel();
        txt_MaTK = new javax.swing.JTextField();
        txt_TenNV = new javax.swing.JTextField();
        txt_SDT = new javax.swing.JTextField();
        txt_ChucVu = new javax.swing.JTextField();
        dc_Ngaysinh = new com.toedter.calendar.JDateChooser();
        rb_Nam = new javax.swing.JRadioButton();
        rb_Nữ = new javax.swing.JRadioButton();
        btn_DoiMK = new javax.swing.JButton();
        btn_TaoTK = new javax.swing.JButton();
        btn_Dangxuat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pn_TieuDe_QLNV.setBackground(new java.awt.Color(0, 255, 255));

        lbl_TieuDe_QLNV.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbl_TieuDe_QLNV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_TieuDe_QLNV.setText("Trí Tuệ Việt");
        lbl_TieuDe_QLNV.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbl_TieuDe_QLNV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pn_TieuDe_QLNVLayout = new javax.swing.GroupLayout(pn_TieuDe_QLNV);
        pn_TieuDe_QLNV.setLayout(pn_TieuDe_QLNVLayout);
        pn_TieuDe_QLNVLayout.setHorizontalGroup(
            pn_TieuDe_QLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_TieuDe_QLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_TieuDe_QLNVLayout.setVerticalGroup(
            pn_TieuDe_QLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_TieuDe_QLNVLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_TieuDe_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btn_TrangChu_QLNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_TrangChu_QLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-home-page-40.png"))); // NOI18N
        btn_TrangChu_QLNV.setText("         Trang chủ");
        btn_TrangChu_QLNV.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btn_TrangChu_QLNV.setMinimumSize(new java.awt.Dimension(97, 90));
        btn_TrangChu_QLNV.setPreferredSize(new java.awt.Dimension(97, 90));
        btn_TrangChu_QLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TrangChu_QLNVActionPerformed(evt);
            }
        });

        btn_QLKH_QLNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_QLKH_QLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-user-40.png"))); // NOI18N
        btn_QLKH_QLNV.setText("    Quản lý khách hàng");
        btn_QLKH_QLNV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_QLKH_QLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLKH_QLNVActionPerformed(evt);
            }
        });

        btn_QLNV_QLNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_QLNV_QLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-manager-40.png"))); // NOI18N
        btn_QLNV_QLNV.setText("     Quản lý nhân viên");
        btn_QLNV_QLNV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_QLNV_QLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLNV_QLNVActionPerformed(evt);
            }
        });

        btn_QLSP_QLNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_QLSP_QLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-book-40.png"))); // NOI18N
        btn_QLSP_QLNV.setText("     Quản lý sản phẩm");
        btn_QLSP_QLNV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_QLSP_QLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLSP_QLNVActionPerformed(evt);
            }
        });

        btn_QLHD_QLNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_QLHD_QLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-file-invoice-dollar-40.png"))); // NOI18N
        btn_QLHD_QLNV.setText("     Quản lý hóa đơn");
        btn_QLHD_QLNV.setActionCommand(" Quản lý hóa đơn");
        btn_QLHD_QLNV.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_QLHD_QLNV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_QLHD_QLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLHD_QLNVActionPerformed(evt);
            }
        });

        btn_ThongKe_QLNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_ThongKe_QLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-analytics-40.png"))); // NOI18N
        btn_ThongKe_QLNV.setText("         Thống kê");
        btn_ThongKe_QLNV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_ThongKe_QLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThongKe_QLNVActionPerformed(evt);
            }
        });

        btn_TaiKhoan_QLNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_TaiKhoan_QLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-user-40_1.png"))); // NOI18N
        btn_TaiKhoan_QLNV.setText("         Tài khoản");
        btn_TaiKhoan_QLNV.setHideActionText(true);
        btn_TaiKhoan_QLNV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_TaiKhoan_QLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TaiKhoan_QLNVActionPerformed(evt);
            }
        });

        pn_TaiKhoan_Menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_Hinh_Menu.setText("Hình ");

        lbl_ChucVu_Menu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btn_DoiMK_Menu.setBackground(new java.awt.Color(102, 255, 102));
        btn_DoiMK_Menu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_DoiMK_Menu.setText("Đổi mật khẩu");
        btn_DoiMK_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DoiMK_MenuActionPerformed(evt);
            }
        });

        btn_DangXuat_Menu.setBackground(new java.awt.Color(102, 255, 102));
        btn_DangXuat_Menu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_DangXuat_Menu.setText("Đăng xuất");
        btn_DangXuat_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DangXuat_MenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_TaiKhoan_MenuLayout = new javax.swing.GroupLayout(pn_TaiKhoan_Menu);
        pn_TaiKhoan_Menu.setLayout(pn_TaiKhoan_MenuLayout);
        pn_TaiKhoan_MenuLayout.setHorizontalGroup(
            pn_TaiKhoan_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_TaiKhoan_MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Hinh_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_TaiKhoan_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_TenTaiKhoan_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_ChucVu_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_TaiKhoan_MenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_DoiMK_Menu)
                .addGap(34, 34, 34)
                .addComponent(btn_DangXuat_Menu)
                .addContainerGap())
        );
        pn_TaiKhoan_MenuLayout.setVerticalGroup(
            pn_TaiKhoan_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_TaiKhoan_MenuLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pn_TaiKhoan_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_Hinh_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pn_TaiKhoan_MenuLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbl_TenTaiKhoan_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_ChucVu_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_TaiKhoan_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_DoiMK_Menu)
                    .addComponent(btn_DangXuat_Menu))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pn_TimKiem_Menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt_TimKiem_Menu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbl_TimKiem_Menu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_TimKiem_Menu.setText("Tìm kiếm sản phẩm theo tên sản phẩm");

        btn_TimKiemMenu.setBackground(new java.awt.Color(102, 255, 102));
        btn_TimKiemMenu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_TimKiemMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-search-24.png"))); // NOI18N
        btn_TimKiemMenu.setText("Tìm kiếm");
        btn_TimKiemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_TimKiem_MenuLayout = new javax.swing.GroupLayout(pn_TimKiem_Menu);
        pn_TimKiem_Menu.setLayout(pn_TimKiem_MenuLayout);
        pn_TimKiem_MenuLayout.setHorizontalGroup(
            pn_TimKiem_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_TimKiem_MenuLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btn_TimKiemMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pn_TimKiem_MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_TimKiem_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_TimKiem_Menu)
                    .addComponent(lbl_TimKiem_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pn_TimKiem_MenuLayout.setVerticalGroup(
            pn_TimKiem_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_TimKiem_MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_TimKiem_Menu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_TimKiem_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_TimKiemMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pn_Menu_QLNVLayout = new javax.swing.GroupLayout(pn_Menu_QLNV);
        pn_Menu_QLNV.setLayout(pn_Menu_QLNVLayout);
        pn_Menu_QLNVLayout.setHorizontalGroup(
            pn_Menu_QLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_TrangChu_QLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_QLNV_QLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_QLSP_QLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_QLHD_QLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_ThongKe_QLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_TaiKhoan_QLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_QLKH_QLNV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_TaiKhoan_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_TimKiem_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_Menu_QLNVLayout.setVerticalGroup(
            pn_Menu_QLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_Menu_QLNVLayout.createSequentialGroup()
                .addComponent(btn_TrangChu_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_QLKH_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_QLNV_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_QLSP_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_QLHD_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ThongKe_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_TaiKhoan_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(pn_TimKiem_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pn_TaiKhoan_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pn_TTTaiKhoan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_Tieu_TaiKhoan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_Tieu_TaiKhoan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Tieu_TaiKhoan.setText("Tài Khoản");
        lbl_Tieu_TaiKhoan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_TTTaiKhoan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_TTTaiKhoan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_TTTaiKhoan.setText("Thông tin tài khoản");

        lbl_MaTK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_MaTK.setText("Mã nhân viên:");

        lbl_TenNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_TenNV.setText("Tên nhân viên:");

        lbl_GioiTinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_GioiTinh.setText("Giới tính:");

        lbl_Ngaysinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_Ngaysinh.setText("Ngày sinh:");

        lbl_SDT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_SDT.setText("Số điện thoại:");

        lbl_ChucVu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_ChucVu.setText("Chức vụ:");

        txt_MaTK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_TenNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_SDT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_ChucVu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_ChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ChucVuActionPerformed(evt);
            }
        });

        btng_NamNu_TaiKhoan.add(rb_Nam);
        rb_Nam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rb_Nam.setText("Nam");

        btng_NamNu_TaiKhoan.add(rb_Nữ);
        rb_Nữ.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rb_Nữ.setText("Nữ");

        btn_DoiMK.setBackground(new java.awt.Color(102, 255, 102));
        btn_DoiMK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_DoiMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlynhanvien/icons/icons8-key-25.png"))); // NOI18N
        btn_DoiMK.setText("Đổi mật khẩu");
        btn_DoiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DoiMKActionPerformed(evt);
            }
        });

        btn_TaoTK.setBackground(new java.awt.Color(102, 255, 102));
        btn_TaoTK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_TaoTK.setText("Tạo tài khoản");
        btn_TaoTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TaoTKActionPerformed(evt);
            }
        });

        btn_Dangxuat.setBackground(new java.awt.Color(102, 255, 102));
        btn_Dangxuat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Dangxuat.setText("Đăng xuất");
        btn_Dangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DangxuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_TTTaiKhoanLayout = new javax.swing.GroupLayout(pn_TTTaiKhoan);
        pn_TTTaiKhoan.setLayout(pn_TTTaiKhoanLayout);
        pn_TTTaiKhoanLayout.setHorizontalGroup(
            pn_TTTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Tieu_TaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_TTTaiKhoanLayout.createSequentialGroup()
                .addGroup(pn_TTTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_TTTaiKhoanLayout.createSequentialGroup()
                        .addGap(454, 454, 454)
                        .addComponent(lbl_TTTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_TTTaiKhoanLayout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addGroup(pn_TTTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_MaTK, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_ChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_GioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(pn_TTTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_TTTaiKhoanLayout.createSequentialGroup()
                                .addComponent(rb_Nam, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(rb_Nữ, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pn_TTTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_ChucVu, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                                .addComponent(txt_SDT, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                                .addComponent(txt_TenNV, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                                .addComponent(txt_MaTK)
                                .addComponent(dc_Ngaysinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pn_TTTaiKhoanLayout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(btn_DoiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addComponent(btn_TaoTK, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180)
                .addComponent(btn_Dangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
        );
        pn_TTTaiKhoanLayout.setVerticalGroup(
            pn_TTTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_TTTaiKhoanLayout.createSequentialGroup()
                .addComponent(lbl_Tieu_TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(lbl_TTTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(pn_TTTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_MaTK, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_MaTK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pn_TTTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pn_TTTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_GioiTinh, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(rb_Nam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rb_Nữ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pn_TTTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dc_Ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pn_TTTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pn_TTTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_TTTaiKhoanLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbl_ChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_TTTaiKhoanLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txt_ChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pn_TTTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_DoiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_TaoTK, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Dangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pn_Menu_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_TTTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pn_TieuDe_QLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pn_TieuDe_QLNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pn_Menu_QLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_TTTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_TrangChu_QLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TrangChu_QLNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_TrangChu_QLNVActionPerformed

    private void btn_QLKH_QLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLKH_QLNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_QLKH_QLNVActionPerformed

    private void btn_QLNV_QLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLNV_QLNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_QLNV_QLNVActionPerformed

    private void btn_QLSP_QLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLSP_QLNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_QLSP_QLNVActionPerformed

    private void btn_QLHD_QLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLHD_QLNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_QLHD_QLNVActionPerformed

    private void btn_ThongKe_QLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThongKe_QLNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ThongKe_QLNVActionPerformed

    private void btn_TaiKhoan_QLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TaiKhoan_QLNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_TaiKhoan_QLNVActionPerformed

    private void btn_DoiMK_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DoiMK_MenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_DoiMK_MenuActionPerformed

    private void btn_DangXuat_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DangXuat_MenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_DangXuat_MenuActionPerformed

    private void btn_TimKiemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_TimKiemMenuActionPerformed

    private void txt_ChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ChucVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ChucVuActionPerformed

    private void btn_DoiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DoiMKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_DoiMKActionPerformed

    private void btn_TaoTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TaoTKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_TaoTKActionPerformed

    private void btn_DangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DangxuatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_DangxuatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaiKhoanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaiKhoanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaiKhoanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaiKhoanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaiKhoanForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_DangXuat_Menu;
    private javax.swing.JButton btn_Dangxuat;
    private javax.swing.JButton btn_DoiMK;
    private javax.swing.JButton btn_DoiMK_Menu;
    private javax.swing.JButton btn_QLHD_QLNV;
    private javax.swing.JButton btn_QLKH_QLNV;
    private javax.swing.JButton btn_QLNV_QLNV;
    private javax.swing.JButton btn_QLSP_QLNV;
    private javax.swing.JButton btn_TaiKhoan_QLNV;
    private javax.swing.JButton btn_TaoTK;
    private javax.swing.JButton btn_ThongKe_QLNV;
    private javax.swing.JButton btn_TimKiemMenu;
    private javax.swing.JButton btn_TrangChu_QLNV;
    private javax.swing.ButtonGroup btng_NamNu_TaiKhoan;
    private com.toedter.calendar.JDateChooser dc_Ngaysinh;
    private javax.swing.JLabel lbl_ChucVu;
    private javax.swing.JLabel lbl_ChucVu_Menu;
    private javax.swing.JLabel lbl_GioiTinh;
    private javax.swing.JLabel lbl_Hinh_Menu;
    private javax.swing.JLabel lbl_MaTK;
    private javax.swing.JLabel lbl_Ngaysinh;
    private javax.swing.JLabel lbl_SDT;
    private javax.swing.JLabel lbl_TTTaiKhoan;
    private javax.swing.JLabel lbl_TenNV;
    private javax.swing.JLabel lbl_TenTaiKhoan_Menu;
    private javax.swing.JLabel lbl_TieuDe_QLNV;
    private javax.swing.JLabel lbl_Tieu_TaiKhoan;
    private javax.swing.JLabel lbl_TimKiem_Menu;
    private javax.swing.JPanel pn_Menu_QLNV;
    private javax.swing.JPanel pn_TTTaiKhoan;
    private javax.swing.JPanel pn_TaiKhoan_Menu;
    private javax.swing.JPanel pn_TieuDe_QLNV;
    private javax.swing.JPanel pn_TimKiem_Menu;
    private javax.swing.JRadioButton rb_Nam;
    private javax.swing.JRadioButton rb_Nữ;
    private javax.swing.JTextField txt_ChucVu;
    private javax.swing.JTextField txt_MaTK;
    private javax.swing.JTextField txt_SDT;
    private javax.swing.JTextField txt_TenNV;
    private javax.swing.JTextField txt_TimKiem_Menu;
    // End of variables declaration//GEN-END:variables
}
